/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.metasyntactic;

public final class R {
    public static final class anim {
        public static final int accelerate_interpolator=0x7f040000;
        public static final int fade=0x7f040001;
        public static final int fade_gallery_item=0x7f040002;
        public static final int fade_reverse=0x7f040003;
        public static final int layout_animation_row_right_slide=0x7f040004;
        public static final int layout_bottom_to_top_slide=0x7f040005;
        public static final int layout_grid_fade=0x7f040006;
        public static final int layout_top_to_bottom_slide=0x7f040007;
        public static final int slide_left=0x7f040008;
        public static final int slide_right=0x7f040009;
        public static final int slide_top_to_bottom=0x7f04000a;
        public static final int wave_scale=0x7f04000b;
    }
    public static final class array {
        /**  Used in auto update location preferences 
         */
        public static final int entries_auto_update_preference=0x7f050004;
        /**  Used in movies sort preferences 
         */
        public static final int entries_movies_sort_preference=0x7f050000;
        /**  Used in reviews provider preferences 
         */
        public static final int entries_reviews_provider_preference=0x7f050003;
        /**  Used in search distance preferences 
         */
        public static final int entries_search_distance_preference=0x7f050002;
        /**  Used in theaters sort preferences 
         */
        public static final int entries_theaters_sort_preference=0x7f050001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int cancel_button_background=0x7f06000a;
        public static final int dark_grey_background=0x7f060007;
        public static final int dimmed_text=0x7f060003;
        public static final int error_text=0x7f060000;
        public static final int grey_text=0x7f060002;
        public static final int gridbackground=0x7f06000c;
        public static final int informational_text=0x7f060005;
        public static final int normal_text=0x7f060001;
        public static final int ok_button_background=0x7f060009;
        public static final int shadow=0x7f060004;
        public static final int title_background=0x7f060008;
        public static final int transparent=0x7f06000b;
        public static final int view_background=0x7f060006;
    }
    public static final class drawable {
        public static final int alternate_background=0x7f02003b;
        public static final int arrow_down=0x7f020000;
        public static final int arrow_down_default=0x7f020001;
        public static final int arrow_down_press=0x7f020002;
        public static final int arrow_up=0x7f020003;
        public static final int arrow_up_default=0x7f020004;
        public static final int arrow_up_press=0x7f020005;
        public static final int background=0x7f020006;
        public static final int bg_maps_details=0x7f020007;
        public static final int black_box=0x7f020008;
        public static final int black_opaque_box=0x7f020009;
        public static final int button=0x7f02000a;
        public static final int dark_header=0x7f02000b;
        public static final int dark_header_dithered=0x7f02000c;
        public static final int dialog_full_dark=0x7f02000d;
        public static final int divider_horizontal_bright=0x7f02000e;
        public static final int down=0x7f02000f;
        public static final int down_1=0x7f020010;
        public static final int expander_ic_maximized=0x7f020011;
        public static final int expander_ic_minimized=0x7f020012;
        public static final int fresh=0x7f020013;
        public static final int gallery_background_1=0x7f020014;
        public static final int ic_menu_allfriends=0x7f020015;
        public static final int ic_menu_home=0x7f020016;
        public static final int ic_menu_manage=0x7f020017;
        public static final int ic_menu_play_new=0x7f020018;
        public static final int ic_menu_star=0x7f020019;
        public static final int ic_menu_start_conversation=0x7f02001a;
        public static final int ic_menu_switch=0x7f02001b;
        public static final int ic_menu_youtube_startscreen=0x7f02001c;
        public static final int icon=0x7f02001d;
        public static final int image_frame=0x7f02001e;
        public static final int image_not_available=0x7f02001f;
        public static final int launcher=0x7f020020;
        public static final int loader2=0x7f020021;
        public static final int loader3=0x7f020022;
        public static final int loading=0x7f020023;
        public static final int more=0x7f020024;
        public static final int movie_droid=0x7f020025;
        public static final int movies=0x7f020026;
        public static final int opaque_box=0x7f020027;
        public static final int rating_blue=0x7f020028;
        public static final int rating_green=0x7f020029;
        public static final int rating_red=0x7f02002a;
        public static final int rating_unknown=0x7f02002b;
        public static final int rating_yellow=0x7f02002c;
        public static final int rotten_faded=0x7f02002d;
        public static final int rotten_full=0x7f02002e;
        public static final int screen_background_orange=0x7f02003a;
        public static final int scrollbar_handle_accelerated_anim2=0x7f02002f;
        public static final int shape_1=0x7f020030;
        public static final int shape_5=0x7f020031;
        public static final int sym_action_call=0x7f020032;
        public static final int sym_action_email=0x7f020033;
        public static final int sym_action_map=0x7f020034;
        public static final int theatres=0x7f020035;
        public static final int transparent_background=0x7f02003c;
        public static final int up=0x7f020036;
        public static final int up_1=0x7f020037;
        public static final int upcoming=0x7f020038;
        public static final int upcoming2=0x7f020039;
    }
    public static final class id {
        public static final int address=0x7f080036;
        public static final int author=0x7f08001d;
        public static final int bottom_bar=0x7f080008;
        public static final int cast=0x7f080016;
        public static final int castlbl=0x7f080015;
        public static final int check=0x7f080028;
        public static final int data=0x7f080026;
        public static final int desc=0x7f08001f;
        public static final int detail=0x7f080018;
        public static final int details=0x7f080019;
        public static final int dialogEdit=0x7f080000;
        public static final int divider=0x7f08000a;
        public static final int divider2=0x7f080007;
        public static final int divider3=0x7f08002c;
        public static final int divider4=0x7f08002f;
        public static final int divider5=0x7f080031;
        public static final int droid=0x7f08001b;
        public static final int genre=0x7f080014;
        public static final int genrelbl=0x7f080013;
        public static final int grid=0x7f08000c;
        public static final int header=0x7f080002;
        public static final int icon=0x7f080027;
        public static final int label=0x7f080025;
        public static final int length=0x7f080012;
        public static final int linearLayout=0x7f08001a;
        public static final int map=0x7f08002d;
        public static final int mapicon=0x7f08002e;
        public static final int maplbl=0x7f08002b;
        public static final int movie=0x7f08002a;
        public static final int name=0x7f080001;
        public static final int next=0x7f080024;
        public static final int phone=0x7f080032;
        public static final int phoneicon=0x7f080033;
        public static final int phonelbl=0x7f080030;
        public static final int poster=0x7f08000d;
        public static final int progress_horizontal=0x7f08001c;
        public static final int rating=0x7f080011;
        public static final int ratingLength=0x7f080006;
        public static final int resultList=0x7f080035;
        public static final int score=0x7f080003;
        public static final int scoreLabel=0x7f080010;
        public static final int scorelbl=0x7f080004;
        public static final int search_bar=0x7f080020;
        public static final int search_edit_frame=0x7f080021;
        public static final int search_go_btn=0x7f080023;
        public static final int search_src_text=0x7f080022;
        public static final int showtimes=0x7f080009;
        public static final int showtimeslbl=0x7f080034;
        public static final int source=0x7f08001e;
        public static final int surface_view=0x7f080037;
        public static final int theater=0x7f080029;
        public static final int thumbnails=0x7f080017;
        public static final int title=0x7f080005;
        public static final int value=0x7f08000b;
        public static final int value1=0x7f08000e;
        public static final int value2=0x7f08000f;
    }
    public static final class layout {
        public static final int alert_dialog_text_entry=0x7f030000;
        public static final int dataview=0x7f030001;
        public static final int headerview=0x7f030002;
        public static final int main=0x7f030003;
        public static final int moviedetails=0x7f030004;
        public static final int moviedetails_item=0x7f030005;
        public static final int moviegrid_anim=0x7f030006;
        public static final int moviegrid_item=0x7f030007;
        public static final int moviepostersynopsis=0x7f030008;
        public static final int moviesummary=0x7f030009;
        public static final int movieview=0x7f03000a;
        public static final int progressbar_1=0x7f03000b;
        public static final int reviewview=0x7f03000c;
        public static final int search_bar=0x7f03000d;
        public static final int settings=0x7f03000e;
        public static final int settings_item=0x7f03000f;
        public static final int showtimedetails=0x7f030010;
        public static final int showtimes=0x7f030011;
        public static final int showtimes_item=0x7f030012;
        public static final int tabs=0x7f030013;
        public static final int theaterdetails=0x7f030014;
        public static final int theaterdetails_item=0x7f030015;
        public static final int theaterlist=0x7f030016;
        public static final int theaters_movie=0x7f030017;
        public static final int theaterview=0x7f030018;
        public static final int upcomingmoviedetails=0x7f030019;
        public static final int videoview=0x7f03001a;
    }
    public static final class string {
        /** About
         */
        public static final int about=0x7f070024;
        /**  Characters that are used for each of the fast-scroll widget that skips directly
        to names starting with this letter.  If your language sorts differently than this,
        please rearrange the alphabet here to be whatever is correct (e.g. Norwegian
        has the three additional letters at the end). 
         */
        public static final int alphabet=0x7f07000e;
        public static final int app_name=0x7f070003;
        /** Auto-Update Location
         */
        public static final int autoupdate_location=0x7f070025;
        /** Blu-ray
         */
        public static final int bluray=0x7f070026;
        /** Bookmarks
         */
        public static final int bookmarks=0x7f070084;
        /** Both
         */
        public static final int both=0x7f070027;
        /** Call
         */
        public static final int call=0x7f070028;
        /** Cancel
         */
        public static final int cancel=0x7f070085;
        /** Cast:
         */
        public static final int cast=0x7f070029;
        /** Change date
         */
        public static final int change_date=0x7f07002a;
        /** City/State or Postal Code
         */
        public static final int citystate_or_postal_code=0x7f07002b;
        /** Could not find location.
         */
        public static final int could_not_find_location_dot=0x7f07002c;
        /** Data for future dates may be incomplete. Reset the search date to the current date to see full listings.
         */
        public static final int data_for_future_dates_may_be_incomplete_dot_reset=0x7f070030;
        /** Director:
         */
        public static final int director=0x7f070031;
        /** Directors:
         */
        public static final int directors=0x7f070032;
        /** Distance
         */
        public static final int distance=0x7f070033;
        /** $%@. %@ - 1 disc.
         */
        public static final int dollarstring_dot_string_one_disc_dot=0x7f070010;
        /** $%@. %@ - %@ discs.
         */
        public static final int dollarstring_dot_string_string_discs_dot=0x7f07000f;
        /** Downloading data
         */
        public static final int downloading_data=0x7f070034;
        /** Downloading poster
         */
        public static final int downloading_poster=0x7f070035;
        /** DVD
         */
        public static final int dvd=0x7f07002d;
        /** DVD/Blu-ray
         */
        public static final int dvdbluray=0x7f07002e;
        /** DVD/Blu-ray details provided by:
         */
        public static final int dvdbluray_details_provided_by=0x7f07002f;
        /** E-mail
         */
        public static final int email=0x7f070036;
        /** E-mail listings
         */
        public static final int email_listings=0x7f070037;
        public static final int enter_location=0x7f070009;
        /** Favorites
         */
        public static final int favorites=0x7f070038;
        /** Format:
         */
        public static final int format=0x7f070039;
        /** Genre:
         */
        public static final int genre=0x7f07003a;
        /** Geolocation services provided by:
         */
        public static final int geolocation_services_provided_by=0x7f07003b;
        /** Graphics by Jeffrey Nee
         */
        public static final int graphics_by_jeffrey_nee=0x7f07003c;
        /** kilometer
         */
        public static final int kilometer=0x7f070080;
        /** kilometers
         */
        public static final int kilometers=0x7f070081;
        /** Last Friday
         */
        public static final int last_friday=0x7f07003d;
        /** Last Monday
         */
        public static final int last_monday=0x7f07003e;
        /** Last Saturday
         */
        public static final int last_saturday=0x7f07003f;
        /** Last Sunday
         */
        public static final int last_sunday=0x7f070040;
        /** Last Thursday
         */
        public static final int last_thursday=0x7f070041;
        /** Last Tuesday
         */
        public static final int last_tuesday=0x7f070042;
        /** Last Wednesday
         */
        public static final int last_wednesday=0x7f070043;
        /** Less than %d %@ away
         */
        public static final int less_than_number_string_away=0x7f070044;
        /** Less than 1 %@ away
         */
        public static final int less_than_one_string_away=0x7f070045;
        /** License
         */
        public static final int license=0x7f070046;
        /** Loading
         */
        public static final int loading=0x7f070086;
        /** Loading poster
         */
        public static final int loading_poster=0x7f070047;
        /** Local results unavailable
         */
        public static final int local_results_unavailable=0x7f070048;
        /** Localized by:
         */
        public static final int localized_by=0x7f070049;
        /** Location
         */
        public static final int location=0x7f07004a;
        /** Map
         */
        public static final int map=0x7f07004b;
        public static final int menu_movie_sort=0x7f070000;
        public static final int menu_movies=0x7f070002;
        public static final int menu_theater_sort=0x7f070001;
        /** mile
         */
        public static final int mile=0x7f070082;
        /** miles
         */
        public static final int miles=0x7f070083;
        /** Movie details provided by:
         */
        public static final int movie_details_provided_by=0x7f07004c;
        /** Movie reviews provided by:
         */
        public static final int movie_reviews_provided_by=0x7f07004d;
        /** Movies
         */
        public static final int movies=0x7f07004e;
        /** My other applications
         */
        public static final int my_other_applications=0x7f070087;
        /** Name
         */
        public static final int name=0x7f07004f;
        /** Network unavailable
         */
        public static final int network_unavailable=0x7f070050;
        /** No information found
         */
        public static final int no_information_found=0x7f070051;
        /** No listings found at '%@' on %@
         */
        public static final int no_listings_found_at_string_on_string=0x7f070088;
        /** No listings found for '%@' at '%@' on %@
         */
        public static final int no_listings_found_for_string_at_string_on_string=0x7f070089;
        /** No listings found for '%@' on %@
         */
        public static final int no_listings_found_for_string_on_string=0x7f07008a;
        /** No more show times available today.
         */
        public static final int no_more_show_times_available_today_dot=0x7f070052;
        /** No results found for '%@'
         */
        public static final int no_results_found_for_string=0x7f070053;
        /** No synopsis available.
         */
        public static final int no_synopsis_available_dot=0x7f070054;
        /** None
         */
        public static final int none=0x7f070055;
        public static final int noreviews=0x7f070006;
        /** Not yet rated
         */
        public static final int not_yet_rated=0x7f070056;
        /** %d hours
         */
        public static final int number_hours=0x7f070015;
        /** %d minutes
         */
        public static final int number_minutes=0x7f070016;
        /** %d months ago
         */
        public static final int number_months_ago=0x7f070017;
        /** %d of %d
         */
        public static final int number_of_number=0x7f070018;
        /** %d %@
         */
        public static final int number_string=0x7f070014;
        /** %d theaters outside search area
         */
        public static final int number_theaters_outside_search_area=0x7f070019;
        /** %d weeks ago
         */
        public static final int number_weeks_ago=0x7f07001a;
        /** %d years ago
         */
        public static final int number_years_ago=0x7f07001b;
        public static final int off=0x7f07000b;
        /** OK
         */
        public static final int ok=0x7f070057;
        public static final int on=0x7f07000a;
        /** 1 hour
         */
        public static final int one_hour=0x7f07001c;
        /** 1 kilometer
         */
        public static final int one_kilometer=0x7f07001d;
        /** 1 mile
         */
        public static final int one_mile=0x7f07001e;
        /** 1 minute
         */
        public static final int one_minute=0x7f07001f;
        /** 1 month ago
         */
        public static final int one_month_ago=0x7f070020;
        /** 1 theater outside search area
         */
        public static final int one_theater_outside_search_area=0x7f070021;
        /** 1 week ago
         */
        public static final int one_week_ago=0x7f070022;
        /** 1 year ago
         */
        public static final int one_year_ago=0x7f070023;
        public static final int options=0x7f070005;
        /** Order tickets for %@
         */
        public static final int order_tickets_for_string=0x7f070058;
        /** Play trailer
         */
        public static final int play_trailer=0x7f070059;
        /** Please enter your location
         */
        public static final int please_enter_your_location=0x7f07005a;
        /** Prioritize Bookmarks
         */
        public static final int prioritize_bookmarks=0x7f07008b;
        /** Project website
         */
        public static final int project_website=0x7f07005b;
        /** Rated:
         */
        public static final int rated=0x7f07005d;
        /** Rated %@
         */
        public static final int rated_string=0x7f07005c;
        /** Read reviews
         */
        public static final int read_reviews=0x7f07005e;
        /** Really close by
         */
        public static final int really_close_by=0x7f07005f;
        /** Really far away
         */
        public static final int really_far_away=0x7f070060;
        /** Release
         */
        public static final int release=0x7f070061;
        /** Release date:
         */
        public static final int release_date=0x7f070062;
        /** Release: %@
         */
        public static final int release_string=0x7f070063;
        /** Reviews
         */
        public static final int reviews=0x7f070064;
        /** Running time:
         */
        public static final int running_time=0x7f070065;
        /** Safari
         */
        public static final int safari=0x7f07008c;
        /** Score
         */
        public static final int score=0x7f070066;
        public static final int search=0x7f070007;
        /** Search Date
         */
        public static final int search_date=0x7f070067;
        /** Search Distance
         */
        public static final int search_distance=0x7f070068;
        public static final int search_label=0x7f070008;
        /** Send Feedback
         */
        public static final int send_feedback=0x7f070069;
        /** Settings
         */
        public static final int settings=0x7f07006a;
        /** Show %d hidden theaters
         */
        public static final int show_number_hidden_theaters=0x7f07006b;
        /** Show 1 hidden theater
         */
        public static final int show_one_hidden_theater=0x7f07006c;
        /** Show times retrieved on %@.
         */
        public static final int show_times_retrieved_on_string_dot=0x7f07006d;
        public static final int showtimes_at=0x7f07000d;
        public static final int showtimes_for=0x7f07000c;
        /** %@. %@
         */
        public static final int string_dot_string=0x7f070013;
        /** %@ (No Online Ticketing)
         */
        public static final int string_no_online_ticketing=0x7f070012;
        /** %@ %@
         */
        public static final int string_string=0x7f070011;
        /** Studio:
         */
        public static final int studio=0x7f07006e;
        public static final int synopsis=0x7f070004;
        /** Theater last reported show times on\n%@.
         */
        public static final int theater_last_reported_show_times_on_string_dot=0x7f07006f;
        /** Theater providers often limit the maximum search distance they will provide data for. As a result, some theaters may not show up for you even if your search distance is set high.
         */
        public static final int theater_providers_often_limit_the_maximum_search=0x7f070070;
        /** Theaters
         */
        public static final int theaters=0x7f070071;
        /** This theater has not yet reported its show times. When they become available, %@ will retrieve them automatically.
         */
        public static final int this_theater_has_not_yet_reported_its_show_times=0x7f070072;
        /** Ticket sales provided by:
         */
        public static final int ticket_sales_provided_by=0x7f070073;
        /** Title
         */
        public static final int title=0x7f070074;
        /** Today
         */
        public static final int today=0x7f070075;
        /** Unknown Distance
         */
        public static final int unknown_distance=0x7f070076;
        /** Unknown release date
         */
        public static final int unknown_release_date=0x7f070077;
        /** Unrated
         */
        public static final int unrated=0x7f070078;
        /** Upcoming
         */
        public static final int upcoming=0x7f070079;
        /** Updating Listings
         */
        public static final int updating_listings=0x7f07008d;
        /** Use Small Fonts
         */
        public static final int use_small_fonts=0x7f07007a;
        /** Visit IMDb
         */
        public static final int visit_imdb=0x7f07007b;
        /** Website
         */
        public static final int website=0x7f07007c;
        /** Written by Cyrus Najmabadi
         */
        public static final int written_by_cyrus_najmabadi=0x7f07007d;
        /** Yesterday
         */
        public static final int yesterday=0x7f07007e;
        /** Your %@'s country is set to: %@\n\nFull support for Now Playing is coming soon to your country, and several features are already available for you to use today! When more features become ready, you will automatically be notified of updates.
         */
        public static final int your_strings_country_is_set_to_string_full_support=0x7f07007f;
    }
}
