// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "google/protobuf/unittest_custom_options.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace protobuf_unittest {

namespace {

const ::google::protobuf::Descriptor* TestMessageWithCustomOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestMessageWithCustomOptions_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TestMessageWithCustomOptions_AnEnum_descriptor_ = NULL;
const ::google::protobuf::Descriptor* CustomOptionFooRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomOptionFooRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CustomOptionFooResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomOptionFooResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* DummyMessageContainingEnum_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DummyMessageContainingEnum_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* DummyMessageContainingEnum_TestEnumType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* DummyMessageInvalidAsOptionType_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DummyMessageInvalidAsOptionType_reflection_ = NULL;
const ::google::protobuf::Descriptor* CustomOptionMinIntegerValues_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomOptionMinIntegerValues_reflection_ = NULL;
const ::google::protobuf::Descriptor* CustomOptionMaxIntegerValues_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomOptionMaxIntegerValues_reflection_ = NULL;
const ::google::protobuf::Descriptor* CustomOptionOtherValues_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CustomOptionOtherValues_reflection_ = NULL;
const ::google::protobuf::Descriptor* SettingRealsFromPositiveInts_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SettingRealsFromPositiveInts_reflection_ = NULL;
const ::google::protobuf::Descriptor* SettingRealsFromNegativeInts_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SettingRealsFromNegativeInts_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOptionType1_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOptionType1_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOptionType2_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOptionType2_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOptionType2_ComplexOptionType4_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOptionType2_ComplexOptionType4_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOptionType3_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOptionType3_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOptionType3_ComplexOptionType5_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOptionType3_ComplexOptionType5_reflection_ = NULL;
const ::google::protobuf::Descriptor* ComplexOpt6_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ComplexOpt6_reflection_ = NULL;
const ::google::protobuf::Descriptor* VariousComplexOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  VariousComplexOptions_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MethodOpt1_descriptor_ = NULL;
const ::google::protobuf::ServiceDescriptor* TestServiceWithCustomOptions_descriptor_ = NULL;

}  // namespace


void protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  TestMessageWithCustomOptions_descriptor_ = file->message_type(0);
  TestMessageWithCustomOptions::default_instance_ = new TestMessageWithCustomOptions();
  static const int TestMessageWithCustomOptions_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMessageWithCustomOptions, field1_),
  };
  TestMessageWithCustomOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestMessageWithCustomOptions_descriptor_,
      TestMessageWithCustomOptions::default_instance_,
      TestMessageWithCustomOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMessageWithCustomOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestMessageWithCustomOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(TestMessageWithCustomOptions));
  TestMessageWithCustomOptions_AnEnum_descriptor_ = TestMessageWithCustomOptions_descriptor_->enum_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestMessageWithCustomOptions_descriptor_, TestMessageWithCustomOptions::default_instance_);
  CustomOptionFooRequest_descriptor_ = file->message_type(1);
  CustomOptionFooRequest::default_instance_ = new CustomOptionFooRequest();
  static const int CustomOptionFooRequest_offsets_[1] = {
  };
  CustomOptionFooRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CustomOptionFooRequest_descriptor_,
      CustomOptionFooRequest::default_instance_,
      CustomOptionFooRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionFooRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionFooRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CustomOptionFooRequest));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CustomOptionFooRequest_descriptor_, CustomOptionFooRequest::default_instance_);
  CustomOptionFooResponse_descriptor_ = file->message_type(2);
  CustomOptionFooResponse::default_instance_ = new CustomOptionFooResponse();
  static const int CustomOptionFooResponse_offsets_[1] = {
  };
  CustomOptionFooResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CustomOptionFooResponse_descriptor_,
      CustomOptionFooResponse::default_instance_,
      CustomOptionFooResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionFooResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionFooResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CustomOptionFooResponse));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CustomOptionFooResponse_descriptor_, CustomOptionFooResponse::default_instance_);
  DummyMessageContainingEnum_descriptor_ = file->message_type(3);
  DummyMessageContainingEnum::default_instance_ = new DummyMessageContainingEnum();
  static const int DummyMessageContainingEnum_offsets_[1] = {
  };
  DummyMessageContainingEnum_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DummyMessageContainingEnum_descriptor_,
      DummyMessageContainingEnum::default_instance_,
      DummyMessageContainingEnum_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DummyMessageContainingEnum, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DummyMessageContainingEnum, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(DummyMessageContainingEnum));
  DummyMessageContainingEnum_TestEnumType_descriptor_ = DummyMessageContainingEnum_descriptor_->enum_type(0);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DummyMessageContainingEnum_descriptor_, DummyMessageContainingEnum::default_instance_);
  DummyMessageInvalidAsOptionType_descriptor_ = file->message_type(4);
  DummyMessageInvalidAsOptionType::default_instance_ = new DummyMessageInvalidAsOptionType();
  static const int DummyMessageInvalidAsOptionType_offsets_[1] = {
  };
  DummyMessageInvalidAsOptionType_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DummyMessageInvalidAsOptionType_descriptor_,
      DummyMessageInvalidAsOptionType::default_instance_,
      DummyMessageInvalidAsOptionType_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DummyMessageInvalidAsOptionType, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DummyMessageInvalidAsOptionType, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(DummyMessageInvalidAsOptionType));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DummyMessageInvalidAsOptionType_descriptor_, DummyMessageInvalidAsOptionType::default_instance_);
  CustomOptionMinIntegerValues_descriptor_ = file->message_type(5);
  CustomOptionMinIntegerValues::default_instance_ = new CustomOptionMinIntegerValues();
  static const int CustomOptionMinIntegerValues_offsets_[1] = {
  };
  CustomOptionMinIntegerValues_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CustomOptionMinIntegerValues_descriptor_,
      CustomOptionMinIntegerValues::default_instance_,
      CustomOptionMinIntegerValues_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionMinIntegerValues, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionMinIntegerValues, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CustomOptionMinIntegerValues));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CustomOptionMinIntegerValues_descriptor_, CustomOptionMinIntegerValues::default_instance_);
  CustomOptionMaxIntegerValues_descriptor_ = file->message_type(6);
  CustomOptionMaxIntegerValues::default_instance_ = new CustomOptionMaxIntegerValues();
  static const int CustomOptionMaxIntegerValues_offsets_[1] = {
  };
  CustomOptionMaxIntegerValues_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CustomOptionMaxIntegerValues_descriptor_,
      CustomOptionMaxIntegerValues::default_instance_,
      CustomOptionMaxIntegerValues_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionMaxIntegerValues, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionMaxIntegerValues, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CustomOptionMaxIntegerValues));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CustomOptionMaxIntegerValues_descriptor_, CustomOptionMaxIntegerValues::default_instance_);
  CustomOptionOtherValues_descriptor_ = file->message_type(7);
  CustomOptionOtherValues::default_instance_ = new CustomOptionOtherValues();
  static const int CustomOptionOtherValues_offsets_[1] = {
  };
  CustomOptionOtherValues_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CustomOptionOtherValues_descriptor_,
      CustomOptionOtherValues::default_instance_,
      CustomOptionOtherValues_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionOtherValues, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CustomOptionOtherValues, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(CustomOptionOtherValues));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CustomOptionOtherValues_descriptor_, CustomOptionOtherValues::default_instance_);
  SettingRealsFromPositiveInts_descriptor_ = file->message_type(8);
  SettingRealsFromPositiveInts::default_instance_ = new SettingRealsFromPositiveInts();
  static const int SettingRealsFromPositiveInts_offsets_[1] = {
  };
  SettingRealsFromPositiveInts_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SettingRealsFromPositiveInts_descriptor_,
      SettingRealsFromPositiveInts::default_instance_,
      SettingRealsFromPositiveInts_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SettingRealsFromPositiveInts, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SettingRealsFromPositiveInts, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SettingRealsFromPositiveInts));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SettingRealsFromPositiveInts_descriptor_, SettingRealsFromPositiveInts::default_instance_);
  SettingRealsFromNegativeInts_descriptor_ = file->message_type(9);
  SettingRealsFromNegativeInts::default_instance_ = new SettingRealsFromNegativeInts();
  static const int SettingRealsFromNegativeInts_offsets_[1] = {
  };
  SettingRealsFromNegativeInts_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SettingRealsFromNegativeInts_descriptor_,
      SettingRealsFromNegativeInts::default_instance_,
      SettingRealsFromNegativeInts_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SettingRealsFromNegativeInts, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SettingRealsFromNegativeInts, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SettingRealsFromNegativeInts));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SettingRealsFromNegativeInts_descriptor_, SettingRealsFromNegativeInts::default_instance_);
  ComplexOptionType1_descriptor_ = file->message_type(10);
  ComplexOptionType1::default_instance_ = new ComplexOptionType1();
  static const int ComplexOptionType1_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType1, foo_),
  };
  ComplexOptionType1_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOptionType1_descriptor_,
      ComplexOptionType1::default_instance_,
      ComplexOptionType1_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType1, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType1, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType1, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOptionType1));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOptionType1_descriptor_, ComplexOptionType1::default_instance_);
  ComplexOptionType2_descriptor_ = file->message_type(11);
  ComplexOptionType2::default_instance_ = new ComplexOptionType2();
  static const int ComplexOptionType2_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, bar_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, baz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, fred_),
  };
  ComplexOptionType2_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOptionType2_descriptor_,
      ComplexOptionType2::default_instance_,
      ComplexOptionType2_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, _unknown_fields_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2, _extensions_),
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOptionType2));
  ComplexOptionType2_ComplexOptionType4_descriptor_ = ComplexOptionType2_descriptor_->nested_type(0);
  ComplexOptionType2_ComplexOptionType4::default_instance_ = new ComplexOptionType2_ComplexOptionType4();
  static const int ComplexOptionType2_ComplexOptionType4_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2_ComplexOptionType4, waldo_),
  };
  ComplexOptionType2_ComplexOptionType4_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOptionType2_ComplexOptionType4_descriptor_,
      ComplexOptionType2_ComplexOptionType4::default_instance_,
      ComplexOptionType2_ComplexOptionType4_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2_ComplexOptionType4, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType2_ComplexOptionType4, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOptionType2_ComplexOptionType4));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOptionType2_ComplexOptionType4_descriptor_, ComplexOptionType2_ComplexOptionType4::default_instance_);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOptionType2_descriptor_, ComplexOptionType2::default_instance_);
  ComplexOptionType3_descriptor_ = file->message_type(12);
  ComplexOptionType3::default_instance_ = new ComplexOptionType3();
  static const int ComplexOptionType3_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3, qux_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3, complexoptiontype5_),
  };
  ComplexOptionType3_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOptionType3_descriptor_,
      ComplexOptionType3::default_instance_,
      ComplexOptionType3_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOptionType3));
  ComplexOptionType3_ComplexOptionType5_descriptor_ = ComplexOptionType3_descriptor_->nested_type(0);
  ComplexOptionType3_ComplexOptionType5::default_instance_ = new ComplexOptionType3_ComplexOptionType5();
  static const int ComplexOptionType3_ComplexOptionType5_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3_ComplexOptionType5, plugh_),
  };
  ComplexOptionType3_ComplexOptionType5_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOptionType3_ComplexOptionType5_descriptor_,
      ComplexOptionType3_ComplexOptionType5::default_instance_,
      ComplexOptionType3_ComplexOptionType5_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3_ComplexOptionType5, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOptionType3_ComplexOptionType5, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOptionType3_ComplexOptionType5));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOptionType3_ComplexOptionType5_descriptor_, ComplexOptionType3_ComplexOptionType5::default_instance_);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOptionType3_descriptor_, ComplexOptionType3::default_instance_);
  ComplexOpt6_descriptor_ = file->message_type(13);
  ComplexOpt6::default_instance_ = new ComplexOpt6();
  static const int ComplexOpt6_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOpt6, xyzzy_),
  };
  ComplexOpt6_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ComplexOpt6_descriptor_,
      ComplexOpt6::default_instance_,
      ComplexOpt6_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOpt6, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComplexOpt6, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(ComplexOpt6));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ComplexOpt6_descriptor_, ComplexOpt6::default_instance_);
  VariousComplexOptions_descriptor_ = file->message_type(14);
  VariousComplexOptions::default_instance_ = new VariousComplexOptions();
  static const int VariousComplexOptions_offsets_[1] = {
  };
  VariousComplexOptions_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      VariousComplexOptions_descriptor_,
      VariousComplexOptions::default_instance_,
      VariousComplexOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VariousComplexOptions, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VariousComplexOptions, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(VariousComplexOptions));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    VariousComplexOptions_descriptor_, VariousComplexOptions::default_instance_);
  MethodOpt1_descriptor_ = file->enum_type(0);
  TestServiceWithCustomOptions_descriptor_ = file->service(0);
  TestMessageWithCustomOptions::default_instance_->InitAsDefaultInstance();
  CustomOptionFooRequest::default_instance_->InitAsDefaultInstance();
  CustomOptionFooResponse::default_instance_->InitAsDefaultInstance();
  DummyMessageContainingEnum::default_instance_->InitAsDefaultInstance();
  DummyMessageInvalidAsOptionType::default_instance_->InitAsDefaultInstance();
  CustomOptionMinIntegerValues::default_instance_->InitAsDefaultInstance();
  CustomOptionMaxIntegerValues::default_instance_->InitAsDefaultInstance();
  CustomOptionOtherValues::default_instance_->InitAsDefaultInstance();
  SettingRealsFromPositiveInts::default_instance_->InitAsDefaultInstance();
  SettingRealsFromNegativeInts::default_instance_->InitAsDefaultInstance();
  ComplexOptionType1::default_instance_->InitAsDefaultInstance();
  ComplexOptionType2::default_instance_->InitAsDefaultInstance();
  ComplexOptionType2_ComplexOptionType4::default_instance_->InitAsDefaultInstance();
  ComplexOptionType3::default_instance_->InitAsDefaultInstance();
  ComplexOptionType3_ComplexOptionType5::default_instance_->InitAsDefaultInstance();
  ComplexOpt6::default_instance_->InitAsDefaultInstance();
  VariousComplexOptions::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  ::google::protobuf::protobuf_BuildDesc_google_2fprotobuf_2fdescriptor_2eproto();
  pool->InternalBuildGeneratedFile(
    "\n-google/protobuf/unittest_custom_option"
    "s.proto\022\021protobuf_unittest\032 google/proto"
    "buf/descriptor.proto\"\241\001\n\034TestMessageWith"
    "CustomOptions\022*\n\006field1\030\001 \001(\tB\032\010\001\301\340\303\035-\341u"
    "\n\002\000\000\000\301\340\303\035-\341u\n\002\000\000\000\"C\n\006AnEnum\022\017\n\013ANENUM_VA"
    "L1\020\001\022\026\n\013ANENUM_VAL2\020\002\032\005\260\206\372\005{\032\020\305\366\311\035\353\374\377\377\305\366"
    "\311\035\353\374\377\377:\020\010\000\340\351\302\035\310\377\377\377\377\377\377\377\377\001\"\030\n\026CustomOption"
    "FooRequest\"\031\n\027CustomOptionFooResponse\"m\n"
    "\032DummyMessageContainingEnum\"O\n\014TestEnumT"
    "ype\022\032\n\026TEST_OPTION_ENUM_TYPE1\020\026\022#\n\026TEST_"
    "OPTION_ENUM_TYPE2\020\351\377\377\377\377\377\377\377\377\001\"!\n\037DummyMes"
    "sageInvalidAsOptionType\"\263\001\n\034CustomOption"
    "MinIntegerValues:\222\001\320\336\262\035\000\350\306\262\035\200\200\200\200\370\377\377\377\377\001\260\274"
    "\262\035\200\200\200\200\200\200\200\200\200\001\200\223\262\035\000\370\365\260\035\000\200\304\260\035\377\377\377\377\017\370\227\260\035\377\377\377\377\377"
    "\377\377\377\377\001\235\365\257\035\000\000\000\000\235\365\257\035\000\000\000\000\221\356\257\035\000\000\000\000\000\000\000\000\221\356\257\035\000\000\000"
    "\000\000\000\000\000\255\215\257\035\000\000\000\200\255\215\257\035\000\000\000\200\231\326\250\035\000\000\000\000\000\000\000\200\231\326\250\035\000\000\000"
    "\000\000\000\000\200\"\272\001\n\034CustomOptionMaxIntegerValues:\231"
    "\001\320\336\262\035\001\350\306\262\035\377\377\377\377\007\260\274\262\035\377\377\377\377\377\377\377\377\177\200\223\262\035\377\377\377\377\017\370\365\260"
    "\035\377\377\377\377\377\377\377\377\377\001\200\304\260\035\376\377\377\377\017\370\227\260\035\376\377\377\377\377\377\377\377\377\001\235\365\257\035\377\377"
    "\377\377\235\365\257\035\377\377\377\377\221\356\257\035\377\377\377\377\377\377\377\377\221\356\257\035\377\377\377\377\377\377\377\377\255\215\257\035\377\377"
    "\377\177\255\215\257\035\377\377\377\177\231\326\250\035\377\377\377\377\377\377\377\177\231\326\250\035\377\377\377\377\377\377\377\177\"\202\001\n\027C"
    "ustomOptionOtherValues:g\350\306\262\035\234\377\377\377\377\377\377\377\377\001\365\337"
    "\243\035\347\207EA\365\337\243\035\347\207EA\351\334\242\035\373Y\214B\312\300\363?\351\334\242\035\373Y\214B\312\300\363?\252\334"
    "\242\035\016Hello, \"World\"\262\331\242\035\013Hello\000World\210\331\242\035\351\377\377"
    "\377\377\377\377\377\377\001\"H\n\034SettingRealsFromPositiveInts:"
    "(\365\337\243\035\000\000@A\365\337\243\035\000\000@A\351\334\242\035\000\000\000\000\000@c@\351\334\242\035\000\000\000\000\000@c"
    "@\"H\n\034SettingRealsFromNegativeInts:(\365\337\243\035\000"
    "\000@\301\365\337\243\035\000\000@\301\351\334\242\035\000\000\000\000\000@c\300\351\334\242\035\000\000\000\000\000@c\300\"+\n\022C"
    "omplexOptionType1\022\013\n\003foo\030\001 \001(\005*\010\010d\020\200\200\200\200\002"
    "\"\301\002\n\022ComplexOptionType2\0222\n\003bar\030\001 \001(\0132%.p"
    "rotobuf_unittest.ComplexOptionType1\022\013\n\003b"
    "az\030\002 \001(\005\022F\n\004fred\030\003 \001(\01328.protobuf_unitte"
    "st.ComplexOptionType2.ComplexOptionType4"
    "\032\227\001\n\022ComplexOptionType4\022\r\n\005waldo\030\001 \001(\0052r"
    "\n\014complex_opt4\022\037.google.protobuf.Message"
    "Options\030\212\365\321\003 \001(\01328.protobuf_unittest.Com"
    "plexOptionType2.ComplexOptionType4*\010\010d\020\200"
    "\200\200\200\002\"\234\001\n\022ComplexOptionType3\022\013\n\003qux\030\001 \001(\005"
    "\022T\n\022complexoptiontype5\030\002 \001(\n28.protobuf_"
    "unittest.ComplexOptionType3.ComplexOptio"
    "nType5\032#\n\022ComplexOptionType5\022\r\n\005plugh\030\003 "
    "\001(\005\"\037\n\013ComplexOpt6\022\020\n\005xyzzy\030\337\277\317\003 \001(\005\"\320\001\n"
    "\025VariousComplexOptions:\266\001\242\342\225\035\002\010*\242\342\225\035\006\330\205\236"
    "\035\304\002\242\342\225\035\010\222\365\235\035\003\010\354\006\252\375\220\035\003\020\333\007\252\375\220\035\006\370\346\227\035\216\005\252\375\220\035\005"
    "\n\003\010\347\005\252\375\220\035\010\n\006\330\205\236\035\317\017\252\375\220\035\n\n\010\222\365\235\035\003\010\330\017\252\375\220\035\010\302\254"
    "\227\035\003\010\345\005\252\375\220\035\013\302\254\227\035\006\330\205\236\035\316\017\252\375\220\035\r\302\254\227\035\010\222\365\235\035\003\010\311\020"
    "\252\375\220\035\005\032\003\010\301\002\322\250\217\035\003\010\263\017\372\336\220\035\002\010\t\372\336\220\035\004\023\030\026\024\343\334\374\034\370\375"
    "\373\034\030\344\334\374\034*6\n\nMethodOpt1\022\023\n\017METHODOPT1_VAL1"
    "\020\001\022\023\n\017METHODOPT1_VAL2\020\0022\216\001\n\034TestServiceW"
    "ithCustomOptions\022c\n\003Foo\022).protobuf_unitt"
    "est.CustomOptionFooRequest\032*.protobuf_un"
    "ittest.CustomOptionFooResponse\"\005\340\372\214\036\002\032\t\220"
    "\262\213\036\323\333\200\313I:2\n\tfile_opt1\022\034.google.protobuf."
    "FileOptions\030\216\235\330\003 \001(\004:8\n\014message_opt1\022\037.g"
    "oogle.protobuf.MessageOptions\030\234\255\330\003 \001(\005:4"
    "\n\nfield_opt1\022\035.google.protobuf.FieldOpti"
    "ons\030\210\274\330\003 \001(\006:8\n\nfield_opt2\022\035.google.prot"
    "obuf.FieldOptions\030\271\241\331\003 \001(\005:\00242:2\n\tenum_o"
    "pt1\022\034.google.protobuf.EnumOptions\030\350\236\331\003 \001"
    "(\017:<\n\017enum_value_opt1\022!.google.protobuf."
    "EnumValueOptions\030\346\240_ \001(\005:8\n\014service_opt1"
    "\022\037.google.protobuf.ServiceOptions\030\242\266\341\003 \001"
    "(\022:U\n\013method_opt1\022\036.google.protobuf.Meth"
    "odOptions\030\254\317\341\003 \001(\0162\035.protobuf_unittest.M"
    "ethodOpt1:4\n\010bool_opt\022\037.google.protobuf."
    "MessageOptions\030\352\253\326\003 \001(\010:5\n\tint32_opt\022\037.g"
    "oogle.protobuf.MessageOptions\030\355\250\326\003 \001(\005:5"
    "\n\tint64_opt\022\037.google.protobuf.MessageOpt"
    "ions\030\306\247\326\003 \001(\003:6\n\nuint32_opt\022\037.google.pro"
    "tobuf.MessageOptions\030\260\242\326\003 \001(\r:6\n\nuint64_"
    "opt\022\037.google.protobuf.MessageOptions\030\337\216\326"
    "\003 \001(\004:6\n\nsint32_opt\022\037.google.protobuf.Me"
    "ssageOptions\030\300\210\326\003 \001(\021:6\n\nsint64_opt\022\037.go"
    "ogle.protobuf.MessageOptions\030\377\202\326\003 \001(\022:7\n"
    "\013fixed32_opt\022\037.google.protobuf.MessageOp"
    "tions\030\323\376\325\003 \001(\007:7\n\013fixed64_opt\022\037.google.p"
    "rotobuf.MessageOptions\030\342\375\325\003 \001(\006:8\n\014sfixe"
    "d32_opt\022\037.google.protobuf.MessageOptions"
    "\030\325\361\325\003 \001(\017:8\n\014sfixed64_opt\022\037.google.proto"
    "buf.MessageOptions\030\343\212\325\003 \001(\020:5\n\tfloat_opt"
    "\022\037.google.protobuf.MessageOptions\030\376\273\324\003 \001"
    "(\002:6\n\ndouble_opt\022\037.google.protobuf.Messa"
    "geOptions\030\315\253\324\003 \001(\001:6\n\nstring_opt\022\037.googl"
    "e.protobuf.MessageOptions\030\305\253\324\003 \001(\t:5\n\tby"
    "tes_opt\022\037.google.protobuf.MessageOptions"
    "\030\226\253\324\003 \001(\014:p\n\010enum_opt\022\037.google.protobuf."
    "MessageOptions\030\221\253\324\003 \001(\0162:.protobuf_unitt"
    "est.DummyMessageContainingEnum.TestEnumT"
    "ype:p\n\020message_type_opt\022\037.google.protobu"
    "f.MessageOptions\030\257\362\323\003 \001(\01322.protobuf_uni"
    "ttest.DummyMessageInvalidAsOptionType:6\n"
    "\004quux\022%.protobuf_unittest.ComplexOptionT"
    "ype1\030\333\340\323\003 \001(\005:^\n\005corge\022%.protobuf_unitte"
    "st.ComplexOptionType1\030\322\336\323\003 \001(\0132%.protobu"
    "f_unittest.ComplexOptionType3:8\n\006grault\022"
    "%.protobuf_unittest.ComplexOptionType2\030\357"
    "\374\322\003 \001(\005:_\n\006garply\022%.protobuf_unittest.Co"
    "mplexOptionType2\030\310\365\322\003 \001(\0132%.protobuf_uni"
    "ttest.ComplexOptionType1:_\n\014complex_opt1"
    "\022\037.google.protobuf.MessageOptions\030\244\334\322\003 \001"
    "(\0132%.protobuf_unittest.ComplexOptionType"
    "1:_\n\014complex_opt2\022\037.google.protobuf.Mess"
    "ageOptions\030\325\217\322\003 \001(\0132%.protobuf_unittest."
    "ComplexOptionType2:_\n\014complex_opt3\022\037.goo"
    "gle.protobuf.MessageOptions\030\357\213\322\003 \001(\0132%.p"
    "rotobuf_unittest.ComplexOptionType3:W\n\013c"
    "omplexopt6\022\037.google.protobuf.MessageOpti"
    "ons\030\314\313\317\003 \001(\n2\036.protobuf_unittest.Complex"
    "Opt6B\t\360\350\301\035\352\255\300\345$", 4335,
  &protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto {
  StaticDescriptorInitializer_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto() {
    protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  }
} static_descriptor_initializer_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto_;

const ::google::protobuf::EnumDescriptor* MethodOpt1_descriptor() {
  if (MethodOpt1_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return MethodOpt1_descriptor_;
}
bool MethodOpt1_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* TestMessageWithCustomOptions_AnEnum_descriptor() {
  if (TestMessageWithCustomOptions_AnEnum_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return TestMessageWithCustomOptions_AnEnum_descriptor_;
}
bool TestMessageWithCustomOptions_AnEnum_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TestMessageWithCustomOptions_AnEnum TestMessageWithCustomOptions::ANENUM_VAL1;
const TestMessageWithCustomOptions_AnEnum TestMessageWithCustomOptions::ANENUM_VAL2;
const TestMessageWithCustomOptions_AnEnum TestMessageWithCustomOptions::AnEnum_MIN;
const TestMessageWithCustomOptions_AnEnum TestMessageWithCustomOptions::AnEnum_MAX;
#endif  // _MSC_VER
const ::std::string TestMessageWithCustomOptions::_default_field1_;
TestMessageWithCustomOptions::TestMessageWithCustomOptions()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    field1_(const_cast< ::std::string*>(&_default_field1_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void TestMessageWithCustomOptions::InitAsDefaultInstance() {}

TestMessageWithCustomOptions::TestMessageWithCustomOptions(const TestMessageWithCustomOptions& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    field1_(const_cast< ::std::string*>(&_default_field1_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

TestMessageWithCustomOptions::~TestMessageWithCustomOptions() {
  if (field1_ != &_default_field1_) {
    delete field1_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* TestMessageWithCustomOptions::descriptor() {
  if (TestMessageWithCustomOptions_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return TestMessageWithCustomOptions_descriptor_;
}

const TestMessageWithCustomOptions& TestMessageWithCustomOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

TestMessageWithCustomOptions* TestMessageWithCustomOptions::default_instance_ = NULL;

TestMessageWithCustomOptions* TestMessageWithCustomOptions::New() const {
  return new TestMessageWithCustomOptions;
}

const ::google::protobuf::Descriptor* TestMessageWithCustomOptions::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* TestMessageWithCustomOptions::GetReflection() const {
  if (TestMessageWithCustomOptions_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return TestMessageWithCustomOptions_reflection_;
}

// ===================================================================

CustomOptionFooRequest::CustomOptionFooRequest()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CustomOptionFooRequest::InitAsDefaultInstance() {}

CustomOptionFooRequest::CustomOptionFooRequest(const CustomOptionFooRequest& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CustomOptionFooRequest::~CustomOptionFooRequest() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CustomOptionFooRequest::descriptor() {
  if (CustomOptionFooRequest_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionFooRequest_descriptor_;
}

const CustomOptionFooRequest& CustomOptionFooRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

CustomOptionFooRequest* CustomOptionFooRequest::default_instance_ = NULL;

CustomOptionFooRequest* CustomOptionFooRequest::New() const {
  return new CustomOptionFooRequest;
}

const ::google::protobuf::Descriptor* CustomOptionFooRequest::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CustomOptionFooRequest::GetReflection() const {
  if (CustomOptionFooRequest_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionFooRequest_reflection_;
}

// ===================================================================

CustomOptionFooResponse::CustomOptionFooResponse()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CustomOptionFooResponse::InitAsDefaultInstance() {}

CustomOptionFooResponse::CustomOptionFooResponse(const CustomOptionFooResponse& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CustomOptionFooResponse::~CustomOptionFooResponse() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CustomOptionFooResponse::descriptor() {
  if (CustomOptionFooResponse_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionFooResponse_descriptor_;
}

const CustomOptionFooResponse& CustomOptionFooResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

CustomOptionFooResponse* CustomOptionFooResponse::default_instance_ = NULL;

CustomOptionFooResponse* CustomOptionFooResponse::New() const {
  return new CustomOptionFooResponse;
}

const ::google::protobuf::Descriptor* CustomOptionFooResponse::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CustomOptionFooResponse::GetReflection() const {
  if (CustomOptionFooResponse_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionFooResponse_reflection_;
}

// ===================================================================

const ::google::protobuf::EnumDescriptor* DummyMessageContainingEnum_TestEnumType_descriptor() {
  if (DummyMessageContainingEnum_TestEnumType_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return DummyMessageContainingEnum_TestEnumType_descriptor_;
}
bool DummyMessageContainingEnum_TestEnumType_IsValid(int value) {
  switch(value) {
    case -23:
    case 22:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const DummyMessageContainingEnum_TestEnumType DummyMessageContainingEnum::TEST_OPTION_ENUM_TYPE1;
const DummyMessageContainingEnum_TestEnumType DummyMessageContainingEnum::TEST_OPTION_ENUM_TYPE2;
const DummyMessageContainingEnum_TestEnumType DummyMessageContainingEnum::TestEnumType_MIN;
const DummyMessageContainingEnum_TestEnumType DummyMessageContainingEnum::TestEnumType_MAX;
#endif  // _MSC_VER
DummyMessageContainingEnum::DummyMessageContainingEnum()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void DummyMessageContainingEnum::InitAsDefaultInstance() {}

DummyMessageContainingEnum::DummyMessageContainingEnum(const DummyMessageContainingEnum& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

DummyMessageContainingEnum::~DummyMessageContainingEnum() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* DummyMessageContainingEnum::descriptor() {
  if (DummyMessageContainingEnum_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return DummyMessageContainingEnum_descriptor_;
}

const DummyMessageContainingEnum& DummyMessageContainingEnum::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

DummyMessageContainingEnum* DummyMessageContainingEnum::default_instance_ = NULL;

DummyMessageContainingEnum* DummyMessageContainingEnum::New() const {
  return new DummyMessageContainingEnum;
}

const ::google::protobuf::Descriptor* DummyMessageContainingEnum::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* DummyMessageContainingEnum::GetReflection() const {
  if (DummyMessageContainingEnum_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return DummyMessageContainingEnum_reflection_;
}

// ===================================================================

DummyMessageInvalidAsOptionType::DummyMessageInvalidAsOptionType()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void DummyMessageInvalidAsOptionType::InitAsDefaultInstance() {}

DummyMessageInvalidAsOptionType::DummyMessageInvalidAsOptionType(const DummyMessageInvalidAsOptionType& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

DummyMessageInvalidAsOptionType::~DummyMessageInvalidAsOptionType() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* DummyMessageInvalidAsOptionType::descriptor() {
  if (DummyMessageInvalidAsOptionType_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return DummyMessageInvalidAsOptionType_descriptor_;
}

const DummyMessageInvalidAsOptionType& DummyMessageInvalidAsOptionType::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

DummyMessageInvalidAsOptionType* DummyMessageInvalidAsOptionType::default_instance_ = NULL;

DummyMessageInvalidAsOptionType* DummyMessageInvalidAsOptionType::New() const {
  return new DummyMessageInvalidAsOptionType;
}

const ::google::protobuf::Descriptor* DummyMessageInvalidAsOptionType::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* DummyMessageInvalidAsOptionType::GetReflection() const {
  if (DummyMessageInvalidAsOptionType_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return DummyMessageInvalidAsOptionType_reflection_;
}

// ===================================================================

CustomOptionMinIntegerValues::CustomOptionMinIntegerValues()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CustomOptionMinIntegerValues::InitAsDefaultInstance() {}

CustomOptionMinIntegerValues::CustomOptionMinIntegerValues(const CustomOptionMinIntegerValues& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CustomOptionMinIntegerValues::~CustomOptionMinIntegerValues() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CustomOptionMinIntegerValues::descriptor() {
  if (CustomOptionMinIntegerValues_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionMinIntegerValues_descriptor_;
}

const CustomOptionMinIntegerValues& CustomOptionMinIntegerValues::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

CustomOptionMinIntegerValues* CustomOptionMinIntegerValues::default_instance_ = NULL;

CustomOptionMinIntegerValues* CustomOptionMinIntegerValues::New() const {
  return new CustomOptionMinIntegerValues;
}

const ::google::protobuf::Descriptor* CustomOptionMinIntegerValues::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CustomOptionMinIntegerValues::GetReflection() const {
  if (CustomOptionMinIntegerValues_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionMinIntegerValues_reflection_;
}

// ===================================================================

CustomOptionMaxIntegerValues::CustomOptionMaxIntegerValues()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CustomOptionMaxIntegerValues::InitAsDefaultInstance() {}

CustomOptionMaxIntegerValues::CustomOptionMaxIntegerValues(const CustomOptionMaxIntegerValues& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CustomOptionMaxIntegerValues::~CustomOptionMaxIntegerValues() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CustomOptionMaxIntegerValues::descriptor() {
  if (CustomOptionMaxIntegerValues_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionMaxIntegerValues_descriptor_;
}

const CustomOptionMaxIntegerValues& CustomOptionMaxIntegerValues::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

CustomOptionMaxIntegerValues* CustomOptionMaxIntegerValues::default_instance_ = NULL;

CustomOptionMaxIntegerValues* CustomOptionMaxIntegerValues::New() const {
  return new CustomOptionMaxIntegerValues;
}

const ::google::protobuf::Descriptor* CustomOptionMaxIntegerValues::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CustomOptionMaxIntegerValues::GetReflection() const {
  if (CustomOptionMaxIntegerValues_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionMaxIntegerValues_reflection_;
}

// ===================================================================

CustomOptionOtherValues::CustomOptionOtherValues()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CustomOptionOtherValues::InitAsDefaultInstance() {}

CustomOptionOtherValues::CustomOptionOtherValues(const CustomOptionOtherValues& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CustomOptionOtherValues::~CustomOptionOtherValues() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CustomOptionOtherValues::descriptor() {
  if (CustomOptionOtherValues_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionOtherValues_descriptor_;
}

const CustomOptionOtherValues& CustomOptionOtherValues::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

CustomOptionOtherValues* CustomOptionOtherValues::default_instance_ = NULL;

CustomOptionOtherValues* CustomOptionOtherValues::New() const {
  return new CustomOptionOtherValues;
}

const ::google::protobuf::Descriptor* CustomOptionOtherValues::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CustomOptionOtherValues::GetReflection() const {
  if (CustomOptionOtherValues_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return CustomOptionOtherValues_reflection_;
}

// ===================================================================

SettingRealsFromPositiveInts::SettingRealsFromPositiveInts()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SettingRealsFromPositiveInts::InitAsDefaultInstance() {}

SettingRealsFromPositiveInts::SettingRealsFromPositiveInts(const SettingRealsFromPositiveInts& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SettingRealsFromPositiveInts::~SettingRealsFromPositiveInts() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SettingRealsFromPositiveInts::descriptor() {
  if (SettingRealsFromPositiveInts_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return SettingRealsFromPositiveInts_descriptor_;
}

const SettingRealsFromPositiveInts& SettingRealsFromPositiveInts::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

SettingRealsFromPositiveInts* SettingRealsFromPositiveInts::default_instance_ = NULL;

SettingRealsFromPositiveInts* SettingRealsFromPositiveInts::New() const {
  return new SettingRealsFromPositiveInts;
}

const ::google::protobuf::Descriptor* SettingRealsFromPositiveInts::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SettingRealsFromPositiveInts::GetReflection() const {
  if (SettingRealsFromPositiveInts_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return SettingRealsFromPositiveInts_reflection_;
}

// ===================================================================

SettingRealsFromNegativeInts::SettingRealsFromNegativeInts()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SettingRealsFromNegativeInts::InitAsDefaultInstance() {}

SettingRealsFromNegativeInts::SettingRealsFromNegativeInts(const SettingRealsFromNegativeInts& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SettingRealsFromNegativeInts::~SettingRealsFromNegativeInts() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SettingRealsFromNegativeInts::descriptor() {
  if (SettingRealsFromNegativeInts_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return SettingRealsFromNegativeInts_descriptor_;
}

const SettingRealsFromNegativeInts& SettingRealsFromNegativeInts::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

SettingRealsFromNegativeInts* SettingRealsFromNegativeInts::default_instance_ = NULL;

SettingRealsFromNegativeInts* SettingRealsFromNegativeInts::New() const {
  return new SettingRealsFromNegativeInts;
}

const ::google::protobuf::Descriptor* SettingRealsFromNegativeInts::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SettingRealsFromNegativeInts::GetReflection() const {
  if (SettingRealsFromNegativeInts_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return SettingRealsFromNegativeInts_reflection_;
}

// ===================================================================


ComplexOptionType1::ComplexOptionType1()
  : ::google::protobuf::Message(),
    _extensions_(&ComplexOptionType1_descriptor_,
                 ::google::protobuf::DescriptorPool::generated_pool(),
                 ::google::protobuf::MessageFactory::generated_factory()),
    _cached_size_(0),
    foo_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOptionType1::InitAsDefaultInstance() {}

ComplexOptionType1::ComplexOptionType1(const ComplexOptionType1& from)
  : ::google::protobuf::Message(),
    _extensions_(&ComplexOptionType1_descriptor_,
                 ::google::protobuf::DescriptorPool::generated_pool(),
                 ::google::protobuf::MessageFactory::generated_factory()),
    _cached_size_(0),
    foo_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOptionType1::~ComplexOptionType1() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ComplexOptionType1::descriptor() {
  if (ComplexOptionType1_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType1_descriptor_;
}

const ComplexOptionType1& ComplexOptionType1::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOptionType1* ComplexOptionType1::default_instance_ = NULL;

ComplexOptionType1* ComplexOptionType1::New() const {
  return new ComplexOptionType1;
}

const ::google::protobuf::Descriptor* ComplexOptionType1::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOptionType1::GetReflection() const {
  if (ComplexOptionType1_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType1_reflection_;
}

// ===================================================================


::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType2_ComplexOptionType4 > > ComplexOptionType2_ComplexOptionType4::complex_opt4(7633546);
ComplexOptionType2_ComplexOptionType4::ComplexOptionType2_ComplexOptionType4()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    waldo_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOptionType2_ComplexOptionType4::InitAsDefaultInstance() {}

ComplexOptionType2_ComplexOptionType4::ComplexOptionType2_ComplexOptionType4(const ComplexOptionType2_ComplexOptionType4& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    waldo_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOptionType2_ComplexOptionType4::~ComplexOptionType2_ComplexOptionType4() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ComplexOptionType2_ComplexOptionType4::descriptor() {
  if (ComplexOptionType2_ComplexOptionType4_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType2_ComplexOptionType4_descriptor_;
}

const ComplexOptionType2_ComplexOptionType4& ComplexOptionType2_ComplexOptionType4::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOptionType2_ComplexOptionType4* ComplexOptionType2_ComplexOptionType4::default_instance_ = NULL;

ComplexOptionType2_ComplexOptionType4* ComplexOptionType2_ComplexOptionType4::New() const {
  return new ComplexOptionType2_ComplexOptionType4;
}

const ::google::protobuf::Descriptor* ComplexOptionType2_ComplexOptionType4::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOptionType2_ComplexOptionType4::GetReflection() const {
  if (ComplexOptionType2_ComplexOptionType4_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType2_ComplexOptionType4_reflection_;
}

// -------------------------------------------------------------------




ComplexOptionType2::ComplexOptionType2()
  : ::google::protobuf::Message(),
    _extensions_(&ComplexOptionType2_descriptor_,
                 ::google::protobuf::DescriptorPool::generated_pool(),
                 ::google::protobuf::MessageFactory::generated_factory()),
    _cached_size_(0),
    bar_(NULL),
    baz_(0),
    fred_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOptionType2::InitAsDefaultInstance() {  bar_ = const_cast< ::protobuf_unittest::ComplexOptionType1*>(&::protobuf_unittest::ComplexOptionType1::default_instance());
  fred_ = const_cast< ::protobuf_unittest::ComplexOptionType2_ComplexOptionType4*>(&::protobuf_unittest::ComplexOptionType2_ComplexOptionType4::default_instance());
}

ComplexOptionType2::ComplexOptionType2(const ComplexOptionType2& from)
  : ::google::protobuf::Message(),
    _extensions_(&ComplexOptionType2_descriptor_,
                 ::google::protobuf::DescriptorPool::generated_pool(),
                 ::google::protobuf::MessageFactory::generated_factory()),
    _cached_size_(0),
    bar_(NULL),
    baz_(0),
    fred_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOptionType2::~ComplexOptionType2() {
  if (this != default_instance_) {
    delete bar_;
    delete fred_;
  }
}

const ::google::protobuf::Descriptor* ComplexOptionType2::descriptor() {
  if (ComplexOptionType2_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType2_descriptor_;
}

const ComplexOptionType2& ComplexOptionType2::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOptionType2* ComplexOptionType2::default_instance_ = NULL;

ComplexOptionType2* ComplexOptionType2::New() const {
  return new ComplexOptionType2;
}

const ::google::protobuf::Descriptor* ComplexOptionType2::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOptionType2::GetReflection() const {
  if (ComplexOptionType2_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType2_reflection_;
}

// ===================================================================


ComplexOptionType3_ComplexOptionType5::ComplexOptionType3_ComplexOptionType5()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    plugh_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOptionType3_ComplexOptionType5::InitAsDefaultInstance() {}

ComplexOptionType3_ComplexOptionType5::ComplexOptionType3_ComplexOptionType5(const ComplexOptionType3_ComplexOptionType5& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    plugh_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOptionType3_ComplexOptionType5::~ComplexOptionType3_ComplexOptionType5() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ComplexOptionType3_ComplexOptionType5::descriptor() {
  if (ComplexOptionType3_ComplexOptionType5_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType3_ComplexOptionType5_descriptor_;
}

const ComplexOptionType3_ComplexOptionType5& ComplexOptionType3_ComplexOptionType5::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOptionType3_ComplexOptionType5* ComplexOptionType3_ComplexOptionType5::default_instance_ = NULL;

ComplexOptionType3_ComplexOptionType5* ComplexOptionType3_ComplexOptionType5::New() const {
  return new ComplexOptionType3_ComplexOptionType5;
}

const ::google::protobuf::Descriptor* ComplexOptionType3_ComplexOptionType5::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOptionType3_ComplexOptionType5::GetReflection() const {
  if (ComplexOptionType3_ComplexOptionType5_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType3_ComplexOptionType5_reflection_;
}

// -------------------------------------------------------------------



ComplexOptionType3::ComplexOptionType3()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    qux_(0),
    complexoptiontype5_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOptionType3::InitAsDefaultInstance() {  complexoptiontype5_ = const_cast< ::protobuf_unittest::ComplexOptionType3_ComplexOptionType5*>(&::protobuf_unittest::ComplexOptionType3_ComplexOptionType5::default_instance());
}

ComplexOptionType3::ComplexOptionType3(const ComplexOptionType3& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    qux_(0),
    complexoptiontype5_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOptionType3::~ComplexOptionType3() {
  if (this != default_instance_) {
    delete complexoptiontype5_;
  }
}

const ::google::protobuf::Descriptor* ComplexOptionType3::descriptor() {
  if (ComplexOptionType3_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType3_descriptor_;
}

const ComplexOptionType3& ComplexOptionType3::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOptionType3* ComplexOptionType3::default_instance_ = NULL;

ComplexOptionType3* ComplexOptionType3::New() const {
  return new ComplexOptionType3;
}

const ::google::protobuf::Descriptor* ComplexOptionType3::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOptionType3::GetReflection() const {
  if (ComplexOptionType3_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOptionType3_reflection_;
}

// ===================================================================


ComplexOpt6::ComplexOpt6()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    xyzzy_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ComplexOpt6::InitAsDefaultInstance() {}

ComplexOpt6::ComplexOpt6(const ComplexOpt6& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    xyzzy_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ComplexOpt6::~ComplexOpt6() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ComplexOpt6::descriptor() {
  if (ComplexOpt6_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOpt6_descriptor_;
}

const ComplexOpt6& ComplexOpt6::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

ComplexOpt6* ComplexOpt6::default_instance_ = NULL;

ComplexOpt6* ComplexOpt6::New() const {
  return new ComplexOpt6;
}

const ::google::protobuf::Descriptor* ComplexOpt6::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ComplexOpt6::GetReflection() const {
  if (ComplexOpt6_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return ComplexOpt6_reflection_;
}

// ===================================================================

VariousComplexOptions::VariousComplexOptions()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void VariousComplexOptions::InitAsDefaultInstance() {}

VariousComplexOptions::VariousComplexOptions(const VariousComplexOptions& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

VariousComplexOptions::~VariousComplexOptions() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* VariousComplexOptions::descriptor() {
  if (VariousComplexOptions_descriptor_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return VariousComplexOptions_descriptor_;
}

const VariousComplexOptions& VariousComplexOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return *default_instance_;
}

VariousComplexOptions* VariousComplexOptions::default_instance_ = NULL;

VariousComplexOptions* VariousComplexOptions::New() const {
  return new VariousComplexOptions;
}

const ::google::protobuf::Descriptor* VariousComplexOptions::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* VariousComplexOptions::GetReflection() const {
  if (VariousComplexOptions_reflection_ == NULL) protobuf_BuildDesc_google_2fprotobuf_2funittest_5fcustom_5foptions_2eproto();
  return VariousComplexOptions_reflection_;
}

// ===================================================================

TestServiceWithCustomOptions::~TestServiceWithCustomOptions() {}

const ::google::protobuf::ServiceDescriptor* TestServiceWithCustomOptions::descriptor() {
  return TestServiceWithCustomOptions_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* TestServiceWithCustomOptions::GetDescriptor() {
  return TestServiceWithCustomOptions_descriptor_;
}

void TestServiceWithCustomOptions::Foo(::google::protobuf::RpcController* controller,
                         const ::protobuf_unittest::CustomOptionFooRequest*,
                         ::protobuf_unittest::CustomOptionFooResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Foo() not implemented.");
  done->Run();
}

void TestServiceWithCustomOptions::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), TestServiceWithCustomOptions_descriptor_);
  switch(method->index()) {
    case 0:
      Foo(controller,
             ::google::protobuf::down_cast<const ::protobuf_unittest::CustomOptionFooRequest*>(request),
             ::google::protobuf::down_cast< ::protobuf_unittest::CustomOptionFooResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& TestServiceWithCustomOptions::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), TestServiceWithCustomOptions_descriptor_);
  switch(method->index()) {
    case 0:
      return ::protobuf_unittest::CustomOptionFooRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& TestServiceWithCustomOptions::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), TestServiceWithCustomOptions_descriptor_);
  switch(method->index()) {
    case 0:
      return ::protobuf_unittest::CustomOptionFooResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

TestServiceWithCustomOptions_Stub::TestServiceWithCustomOptions_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
TestServiceWithCustomOptions_Stub::TestServiceWithCustomOptions_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
TestServiceWithCustomOptions_Stub::~TestServiceWithCustomOptions_Stub() {
  if (owns_channel_) delete channel_;
}

void TestServiceWithCustomOptions_Stub::Foo(::google::protobuf::RpcController* controller,
                              const ::protobuf_unittest::CustomOptionFooRequest* request,
                              ::protobuf_unittest::CustomOptionFooResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(TestServiceWithCustomOptions_descriptor_->method(0),
                       controller, request, response, done);
}
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint64 > > file_opt1(7736974);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > message_opt1(7739036);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint64 > > field_opt1(7740936);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > field_opt2(7753913);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > enum_opt1(7753576);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > enum_value_opt1(1560678);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 > > service_opt1(7887650);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
  ::google::protobuf::internal::EnumTypeTraits< protobuf_unittest::MethodOpt1 > > method_opt1(7890860);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< bool > > bool_opt(7706090);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > int32_opt(7705709);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 > > int64_opt(7705542);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 > > uint32_opt(7704880);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint64 > > uint64_opt(7702367);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > sint32_opt(7701568);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 > > sint64_opt(7700863);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 > > fixed32_opt(7700307);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint64 > > fixed64_opt(7700194);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > sfixed32_opt(7698645);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int64 > > sfixed64_opt(7685475);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< float > > float_opt(7675390);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::PrimitiveTypeTraits< double > > double_opt(7673293);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::StringTypeTraits > string_opt(7673285);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::StringTypeTraits > bytes_opt(7673238);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::EnumTypeTraits< ::protobuf_unittest::DummyMessageContainingEnum_TestEnumType > > enum_opt(7673233);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::DummyMessageInvalidAsOptionType > > message_type_opt(7665967);
::google::protobuf::internal::ExtensionIdentifier< ::protobuf_unittest::ComplexOptionType1,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > quux(7663707);
::google::protobuf::internal::ExtensionIdentifier< ::protobuf_unittest::ComplexOptionType1,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType3 > > corge(7663442);
::google::protobuf::internal::ExtensionIdentifier< ::protobuf_unittest::ComplexOptionType2,
  ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 > > grault(7650927);
::google::protobuf::internal::ExtensionIdentifier< ::protobuf_unittest::ComplexOptionType2,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType1 > > garply(7649992);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType1 > > complex_opt1(7646756);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType2 > > complex_opt2(7636949);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOptionType3 > > complex_opt3(7636463);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
  ::google::protobuf::internal::MessageTypeTraits< ::protobuf_unittest::ComplexOpt6 > > complexopt6(7595468);

}  // namespace protobuf_unittest
