// Generated by the protocol buffer compiler.  DO NOT EDIT!

@class PBFieldAccessorTable;
@class PBGeneratedMessage_Builder;
@class RawMessageSet;
@class RawMessageSet_Builder;
@class RawMessageSet_Item;
@class RawMessageSet_Item_Builder;
@class TestMessageSet;
@class TestMessageSetContainer;
@class TestMessageSetContainer_Builder;
@class TestMessageSetExtension1;
@class TestMessageSetExtension1_Builder;
@class TestMessageSetExtension2;
@class TestMessageSetExtension2_Builder;
@class TestMessageSet_Builder;

@interface UnittestMsetProtoRoot : NSObject {
}
+ (PBFileDescriptor*) descriptor;
+ (PBFileDescriptor*) buildDescriptor;
@end

@interface TestMessageSet : PBExtendableMessage {
 @private
  int32_t memoizedSerializedSize;
}
+ (TestMessageSet*) defaultInstance;
- (TestMessageSet*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (TestMessageSet_Builder*) newBuilder;
- (TestMessageSet_Builder*) newBuilderForType;
+ (TestMessageSet_Builder*) newBuilderWithTestMessageSet:(TestMessageSet*) prototype;
+ (TestMessageSet*) parseFromData:(NSData*) data;
+ (TestMessageSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSet*) parseFromInputStream:(NSInputStream*) input;
+ (TestMessageSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessageSet_Builder : PBExtendableBuilder {
 @private
  TestMessageSet* result;
}
@property (retain) TestMessageSet* result;
- (TestMessageSet_Builder*) clear;
- (TestMessageSet_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (TestMessageSet*) defaultInstanceForType;
- (TestMessageSet*) build;
- (TestMessageSet*) buildPartial;
- (TestMessageSet_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (TestMessageSet_Builder*) mergeFromTestMessageSet:(TestMessageSet*) other;
- (TestMessageSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestMessageSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessageSetContainer : PBGeneratedMessage {
 @private
  int32_t memoizedSerializedSize;
  BOOL hasMessageSet;
  TestMessageSet* messageSet;
}
@property (readonly) BOOL hasMessageSet;
@property (retain, readonly) TestMessageSet* messageSet;
+ (TestMessageSetContainer*) defaultInstance;
- (TestMessageSetContainer*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (TestMessageSetContainer_Builder*) newBuilder;
- (TestMessageSetContainer_Builder*) newBuilderForType;
+ (TestMessageSetContainer_Builder*) newBuilderWithTestMessageSetContainer:(TestMessageSetContainer*) prototype;
+ (TestMessageSetContainer*) parseFromData:(NSData*) data;
+ (TestMessageSetContainer*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetContainer*) parseFromInputStream:(NSInputStream*) input;
+ (TestMessageSetContainer*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetContainer*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestMessageSetContainer*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessageSetContainer_Builder : PBGeneratedMessage_Builder {
 @private
  TestMessageSetContainer* result;
}
@property (retain) TestMessageSetContainer* result;
- (TestMessageSetContainer_Builder*) clear;
- (TestMessageSetContainer_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (TestMessageSetContainer*) defaultInstanceForType;
- (TestMessageSetContainer*) build;
- (TestMessageSetContainer*) buildPartial;
- (TestMessageSetContainer_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (TestMessageSetContainer_Builder*) mergeFromTestMessageSetContainer:(TestMessageSetContainer*) other;
- (TestMessageSetContainer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestMessageSetContainer_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageSet;
- (TestMessageSet*) messageSet;
- (id<PBMessage_Builder>) setMessageSet:(TestMessageSet*) value;
- (id<PBMessage_Builder>) setMessageSetBuilder:(TestMessageSet_Builder*) builderForValue;
- (id<PBMessage_Builder>) mergeMessageSet:(TestMessageSet*) value;
- (id<PBMessage_Builder>) clearMessageSet;
@end

@interface TestMessageSetExtension1 : PBGeneratedMessage {
 @private
  int32_t memoizedSerializedSize;
  BOOL hasI;
  int32_t i;
}
@property (readonly) BOOL hasI;
@property (readonly) int32_t i;
+ (TestMessageSetExtension1*) defaultInstance;
- (TestMessageSetExtension1*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (TestMessageSetExtension1_Builder*) newBuilder;
- (TestMessageSetExtension1_Builder*) newBuilderForType;
+ (TestMessageSetExtension1_Builder*) newBuilderWithTestMessageSetExtension1:(TestMessageSetExtension1*) prototype;
+ (TestMessageSetExtension1*) parseFromData:(NSData*) data;
+ (TestMessageSetExtension1*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetExtension1*) parseFromInputStream:(NSInputStream*) input;
+ (TestMessageSetExtension1*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetExtension1*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestMessageSetExtension1*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessageSetExtension1_Builder : PBGeneratedMessage_Builder {
 @private
  TestMessageSetExtension1* result;
}
@property (retain) TestMessageSetExtension1* result;
- (TestMessageSetExtension1_Builder*) clear;
- (TestMessageSetExtension1_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (TestMessageSetExtension1*) defaultInstanceForType;
- (TestMessageSetExtension1*) build;
- (TestMessageSetExtension1*) buildPartial;
- (TestMessageSetExtension1_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (TestMessageSetExtension1_Builder*) mergeFromTestMessageSetExtension1:(TestMessageSetExtension1*) other;
- (TestMessageSetExtension1_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestMessageSetExtension1_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasI;
- (int32_t) i;
- (TestMessageSetExtension1_Builder*) setI:(int32_t) value;
- (TestMessageSetExtension1_Builder*) clearI;
@end

@interface TestMessageSetExtension2 : PBGeneratedMessage {
 @private
  int32_t memoizedSerializedSize;
  BOOL hasStr;
  NSString* str;
}
@property (readonly) BOOL hasStr;
@property (retain, readonly) NSString* str;
+ (TestMessageSetExtension2*) defaultInstance;
- (TestMessageSetExtension2*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (TestMessageSetExtension2_Builder*) newBuilder;
- (TestMessageSetExtension2_Builder*) newBuilderForType;
+ (TestMessageSetExtension2_Builder*) newBuilderWithTestMessageSetExtension2:(TestMessageSetExtension2*) prototype;
+ (TestMessageSetExtension2*) parseFromData:(NSData*) data;
+ (TestMessageSetExtension2*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetExtension2*) parseFromInputStream:(NSInputStream*) input;
+ (TestMessageSetExtension2*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessageSetExtension2*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestMessageSetExtension2*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessageSetExtension2_Builder : PBGeneratedMessage_Builder {
 @private
  TestMessageSetExtension2* result;
}
@property (retain) TestMessageSetExtension2* result;
- (TestMessageSetExtension2_Builder*) clear;
- (TestMessageSetExtension2_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (TestMessageSetExtension2*) defaultInstanceForType;
- (TestMessageSetExtension2*) build;
- (TestMessageSetExtension2*) buildPartial;
- (TestMessageSetExtension2_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (TestMessageSetExtension2_Builder*) mergeFromTestMessageSetExtension2:(TestMessageSetExtension2*) other;
- (TestMessageSetExtension2_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestMessageSetExtension2_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStr;
- (NSString*) str;
- (TestMessageSetExtension2_Builder*) setStr:(NSString*) value;
- (TestMessageSetExtension2_Builder*) clearStr;
@end

@interface RawMessageSet : PBGeneratedMessage {
 @private
  int32_t memoizedSerializedSize;
  NSMutableArray* mutableItemList;
}
- (NSArray*) itemList;
- (RawMessageSet_Item*) itemAtIndex:(int32_t) index;
+ (RawMessageSet*) defaultInstance;
- (RawMessageSet*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (RawMessageSet_Builder*) newBuilder;
- (RawMessageSet_Builder*) newBuilderForType;
+ (RawMessageSet_Builder*) newBuilderWithRawMessageSet:(RawMessageSet*) prototype;
+ (RawMessageSet*) parseFromData:(NSData*) data;
+ (RawMessageSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RawMessageSet*) parseFromInputStream:(NSInputStream*) input;
+ (RawMessageSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RawMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RawMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RawMessageSet_Item : PBGeneratedMessage {
 @private
  int32_t memoizedSerializedSize;
  BOOL hasTypeId;
  int32_t typeId;
  BOOL hasMessage;
  NSData* message;
}
@property (readonly) BOOL hasTypeId;
@property (readonly) int32_t typeId;
@property (readonly) BOOL hasMessage;
@property (retain, readonly) NSData* message;
+ (RawMessageSet_Item*) defaultInstance;
- (RawMessageSet_Item*) defaultInstanceForType;
+ (PBDescriptor*) descriptor;
- (PBFieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
+ (RawMessageSet_Item_Builder*) newBuilder;
- (RawMessageSet_Item_Builder*) newBuilderForType;
+ (RawMessageSet_Item_Builder*) newBuilderWithRawMessageSet_Item:(RawMessageSet_Item*) prototype;
+ (RawMessageSet_Item*) parseFromData:(NSData*) data;
+ (RawMessageSet_Item*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RawMessageSet_Item*) parseFromInputStream:(NSInputStream*) input;
+ (RawMessageSet_Item*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RawMessageSet_Item*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RawMessageSet_Item*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RawMessageSet_Item_Builder : PBGeneratedMessage_Builder {
 @private
  RawMessageSet_Item* result;
}
@property (retain) RawMessageSet_Item* result;
- (RawMessageSet_Item_Builder*) clear;
- (RawMessageSet_Item_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (RawMessageSet_Item*) defaultInstanceForType;
- (RawMessageSet_Item*) build;
- (RawMessageSet_Item*) buildPartial;
- (RawMessageSet_Item_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (RawMessageSet_Item_Builder*) mergeFromRawMessageSet_Item:(RawMessageSet_Item*) other;
- (RawMessageSet_Item_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RawMessageSet_Item_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTypeId;
- (int32_t) typeId;
- (RawMessageSet_Item_Builder*) setTypeId:(int32_t) value;
- (RawMessageSet_Item_Builder*) clearTypeId;

- (BOOL) hasMessage;
- (NSData*) message;
- (RawMessageSet_Item_Builder*) setMessage:(NSData*) value;
- (RawMessageSet_Item_Builder*) clearMessage;
@end

@interface RawMessageSet_Builder : PBGeneratedMessage_Builder {
 @private
  RawMessageSet* result;
}
@property (retain) RawMessageSet* result;
- (RawMessageSet_Builder*) clear;
- (RawMessageSet_Builder*) clone;
- (PBDescriptor*) descriptorForType;
- (RawMessageSet*) defaultInstanceForType;
- (RawMessageSet*) build;
- (RawMessageSet*) buildPartial;
- (RawMessageSet_Builder*) mergeFromMessage:(id<PBMessage>) other;
- (RawMessageSet_Builder*) mergeFromRawMessageSet:(RawMessageSet*) other;
- (RawMessageSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RawMessageSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) itemList;
- (RawMessageSet_Item*) itemAtIndex:(int32_t) index;
- (RawMessageSet_Builder*) replaceItemAtIndex:(int32_t) index withItem:(RawMessageSet_Item*) value;
- (RawMessageSet_Builder*) addItem:(RawMessageSet_Item*) value;
- (RawMessageSet_Builder*) addAllItem:(NSArray*) values;
- (RawMessageSet_Builder*) clearItemList;
@end

