// Generated by the protocol buffer compiler.  DO NOT EDIT!

@class GeneratedMessage_FieldAccessorTable;
@class GeneratedMessage_Builder;
@class FileDescriptorSet;
@class FileDescriptorSet_Builder;
@class FileDescriptorProto;
@class FileDescriptorProto_Builder;
@class DescriptorProto;
@class DescriptorProto_Builder;
@class ExtensionRange;
@class ExtensionRange_Builder;
@class FieldDescriptorProto;
@class FieldDescriptorProto_Builder;
@class Type;
@class Label;
@class EnumDescriptorProto;
@class EnumDescriptorProto_Builder;
@class EnumValueDescriptorProto;
@class EnumValueDescriptorProto_Builder;
@class ServiceDescriptorProto;
@class ServiceDescriptorProto_Builder;
@class MethodDescriptorProto;
@class MethodDescriptorProto_Builder;
@class FileOptions;
@class FileOptions_Builder;
@class OptimizeMode;
@class MessageOptions;
@class MessageOptions_Builder;
@class FieldOptions;
@class FieldOptions_Builder;
@class CType;
@class EnumOptions;
@class EnumOptions_Builder;
@class EnumValueOptions;
@class EnumValueOptions_Builder;
@class ServiceOptions;
@class ServiceOptions_Builder;
@class MethodOptions;
@class MethodOptions_Builder;

@interface Descriptor : NSObject {
}
+ (FileDescriptor*) getDescriptor;
+ (FileDescriptor*) buildDescriptor;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_FileDescriptorSet_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_FileDescriptorSet_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_FileDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_FileDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_DescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_DescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_DescriptorProto_ExtensionRange_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_DescriptorProto_ExtensionRange_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_FieldDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_FieldDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_EnumDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_EnumDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_EnumValueDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_EnumValueDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_ServiceDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_ServiceDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_MethodDescriptorProto_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_MethodDescriptorProto_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_FileOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_FileOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_MessageOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_MessageOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_FieldOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_FieldOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_EnumOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_EnumOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_EnumValueOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_EnumValueOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_ServiceOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_ServiceOptions_fieldAccessorTable;
+ (ProtocolBufferDescriptor*) internal_static_google_protobuf_MethodOptions_descriptor;
+ (GeneratedMessage_FieldAccessorTable*) internal_static_google_protobuf_MethodOptions_fieldAccessorTable;
@end

@interface FileDescriptorSet : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // repeated .google.protobuf.FileDescriptorProto file = 1;
    NSMutableArray* file_;
}
@property (retain) NSMutableArray* file_;
- (NSArray*) getFileList;
- (int32_t) getFileCount;
- (FileDescriptorProto*) getFile:(int32_t) index;
+ (FileDescriptorSet*) getDefaultInstance;
- (FileDescriptorSet*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (FileDescriptorSet_Builder*) newBuilder;
- (FileDescriptorSet_Builder*) newBuilderForType;
+ (FileDescriptorSet_Builder*) newBuilderWithFileDescriptorSet:(FileDescriptorSet*) prototype;
+ (FileDescriptorSet*) parseFromData:(NSData*) data;
+ (FileDescriptorSet*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileDescriptorSet*) parseFromInputStream:(NSInputStream*) input;
+ (FileDescriptorSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileDescriptorSet*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (FileDescriptorSet*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface FileDescriptorSet_Builder : GeneratedMessage_Builder {
@private
    FileDescriptorSet* result;
}
@property (retain) FileDescriptorSet* result;
// Construct using FileDescriptorSet.newBuilder()
- (FileDescriptorSet_Builder*) clear;
- (FileDescriptorSet_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (FileDescriptorSet*) getDefaultInstanceForType;
- (FileDescriptorSet*) build;
- (FileDescriptorSet*) buildParsed;
- (FileDescriptorSet*) buildPartial;
- (FileDescriptorSet_Builder*) mergeFromMessage:(id<Message>) other;
- (FileDescriptorSet_Builder*) mergeFromFileDescriptorSet:(FileDescriptorSet*) other;
- (FileDescriptorSet_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (FileDescriptorSet_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// repeated .google.protobuf.FileDescriptorProto file = 1;
- (NSArray*) getFileList;
- (int32_t) getFileCount;
- (FileDescriptorProto*) getFile:(int32_t) index;
- (FileDescriptorSet_Builder*) setFile:(int32_t) index value:(FileDescriptorProto*) value;
- (FileDescriptorSet_Builder*) setFile:(int32_t) index builderForValue:(FileDescriptorProto_Builder*) builderForValue;
- (FileDescriptorSet_Builder*) addFileBuilder:(FileDescriptorProto_Builder*) builderForValue;
- (FileDescriptorSet_Builder*) addAllFile:(NSArray*) values;
- (FileDescriptorSet_Builder*) clearFile;
- (FileDescriptorSet_Builder*) addFile:(FileDescriptorProto*) value;
@end

@interface FileDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional string package = 2;
    BOOL hasPackage;
    NSString* package_;
    // repeated string dependency = 3;
    NSMutableArray* dependency_;
    // repeated .google.protobuf.DescriptorProto message_type = 4;
    NSMutableArray* messageType_;
    // repeated .google.protobuf.EnumDescriptorProto enum_type = 5;
    NSMutableArray* enumType_;
    // repeated .google.protobuf.ServiceDescriptorProto service = 6;
    NSMutableArray* service_;
    // repeated .google.protobuf.FieldDescriptorProto extension = 7;
    NSMutableArray* extension_;
    // optional .google.protobuf.FileOptions options = 8;
    BOOL hasOptions;
    FileOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasPackage;
@property (retain) NSString* package_;
@property (retain) NSMutableArray* dependency_;
@property (retain) NSMutableArray* messageType_;
@property (retain) NSMutableArray* enumType_;
@property (retain) NSMutableArray* service_;
@property (retain) NSMutableArray* extension_;
@property BOOL hasOptions;
@property (retain) FileOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasPackage;
- (NSString*) getPackage;
- (NSArray*) getDependencyList;
- (int32_t) getDependencyCount;
- (NSString*) getDependency:(int32_t) index;
- (NSArray*) getMessageTypeList;
- (int32_t) getMessageTypeCount;
- (DescriptorProto*) getMessageType:(int32_t) index;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (EnumDescriptorProto*) getEnumType:(int32_t) index;
- (NSArray*) getServiceList;
- (int32_t) getServiceCount;
- (ServiceDescriptorProto*) getService:(int32_t) index;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (FieldDescriptorProto*) getExtension:(int32_t) index;
- (FileOptions*) getOptions;
+ (FileDescriptorProto*) getDefaultInstance;
- (FileDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (FileDescriptorProto_Builder*) newBuilder;
- (FileDescriptorProto_Builder*) newBuilderForType;
+ (FileDescriptorProto_Builder*) newBuilderWithFileDescriptorProto:(FileDescriptorProto*) prototype;
+ (FileDescriptorProto*) parseFromData:(NSData*) data;
+ (FileDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (FileDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (FileDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface FileDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    FileDescriptorProto* result;
}
@property (retain) FileDescriptorProto* result;
// Construct using FileDescriptorProto.newBuilder()
- (FileDescriptorProto_Builder*) clear;
- (FileDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (FileDescriptorProto*) getDefaultInstanceForType;
- (FileDescriptorProto*) build;
- (FileDescriptorProto*) buildParsed;
- (FileDescriptorProto*) buildPartial;
- (FileDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (FileDescriptorProto_Builder*) mergeFromFileDescriptorProto:(FileDescriptorProto*) other;
- (FileDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (FileDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (FileDescriptorProto_Builder*) setName:(NSString*) value;
- (FileDescriptorProto_Builder*) clearName;

// optional string package = 2;
- (BOOL) hasPackage;
- (NSString*) getPackage;
- (FileDescriptorProto_Builder*) setPackage:(NSString*) value;
- (FileDescriptorProto_Builder*) clearPackage;

// repeated string dependency = 3;
- (NSArray*) getDependencyList;
- (int32_t) getDependencyCount;
- (NSString*) getDependency:(int32_t) index;
- (FileDescriptorProto_Builder*) setDependency:(int32_t) index value:(NSString*) value;
- (FileDescriptorProto_Builder*) addDependency:(NSString*) value;
- (FileDescriptorProto_Builder*) addAllDependency:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearDependency;

// repeated .google.protobuf.DescriptorProto message_type = 4;
- (NSArray*) getMessageTypeList;
- (int32_t) getMessageTypeCount;
- (DescriptorProto*) getMessageType:(int32_t) index;
- (FileDescriptorProto_Builder*) setMessageType:(int32_t) index value:(DescriptorProto*) value;
- (FileDescriptorProto_Builder*) setMessageType:(int32_t) index builderForValue:(DescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addMessageTypeBuilder:(DescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addAllMessageType:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearMessageType;
- (FileDescriptorProto_Builder*) addMessageType:(DescriptorProto*) value;

// repeated .google.protobuf.EnumDescriptorProto enum_type = 5;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (EnumDescriptorProto*) getEnumType:(int32_t) index;
- (FileDescriptorProto_Builder*) setEnumType:(int32_t) index value:(EnumDescriptorProto*) value;
- (FileDescriptorProto_Builder*) setEnumType:(int32_t) index builderForValue:(EnumDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addEnumTypeBuilder:(EnumDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearEnumType;
- (FileDescriptorProto_Builder*) addEnumType:(EnumDescriptorProto*) value;

// repeated .google.protobuf.ServiceDescriptorProto service = 6;
- (NSArray*) getServiceList;
- (int32_t) getServiceCount;
- (ServiceDescriptorProto*) getService:(int32_t) index;
- (FileDescriptorProto_Builder*) setService:(int32_t) index value:(ServiceDescriptorProto*) value;
- (FileDescriptorProto_Builder*) setService:(int32_t) index builderForValue:(ServiceDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addServiceBuilder:(ServiceDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addAllService:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearService;
- (FileDescriptorProto_Builder*) addService:(ServiceDescriptorProto*) value;

// repeated .google.protobuf.FieldDescriptorProto extension = 7;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (FieldDescriptorProto*) getExtension:(int32_t) index;
- (FileDescriptorProto_Builder*) setExtension:(int32_t) index value:(FieldDescriptorProto*) value;
- (FileDescriptorProto_Builder*) setExtension:(int32_t) index builderForValue:(FieldDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addExtensionBuilder:(FieldDescriptorProto_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearExtension;
- (FileDescriptorProto_Builder*) addExtension:(FieldDescriptorProto*) value;

// optional .google.protobuf.FileOptions options = 8;
- (BOOL) hasOptions;
- (FileOptions*) getOptions;
- (id<Message_Builder>) setOptions:(FileOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(FileOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(FileOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface DescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.FieldDescriptorProto field = 2;
    NSMutableArray* field_;
    // repeated .google.protobuf.FieldDescriptorProto extension = 6;
    NSMutableArray* extension_;
    // repeated .google.protobuf.DescriptorProto nested_type = 3;
    NSMutableArray* nestedType_;
    // repeated .google.protobuf.EnumDescriptorProto enum_type = 4;
    NSMutableArray* enumType_;
    // repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;
    NSMutableArray* extensionRange_;
    // optional .google.protobuf.MessageOptions options = 7;
    BOOL hasOptions;
    MessageOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* field_;
@property (retain) NSMutableArray* extension_;
@property (retain) NSMutableArray* nestedType_;
@property (retain) NSMutableArray* enumType_;
@property (retain) NSMutableArray* extensionRange_;
@property BOOL hasOptions;
@property (retain) MessageOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getFieldList;
- (int32_t) getFieldCount;
- (FieldDescriptorProto*) getField:(int32_t) index;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (FieldDescriptorProto*) getExtension:(int32_t) index;
- (NSArray*) getNestedTypeList;
- (int32_t) getNestedTypeCount;
- (DescriptorProto*) getNestedType:(int32_t) index;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (EnumDescriptorProto*) getEnumType:(int32_t) index;
- (NSArray*) getExtensionRangeList;
- (int32_t) getExtensionRangeCount;
- (ExtensionRange*) getExtensionRange:(int32_t) index;
- (MessageOptions*) getOptions;
+ (DescriptorProto*) getDefaultInstance;
- (DescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (DescriptorProto_Builder*) newBuilder;
- (DescriptorProto_Builder*) newBuilderForType;
+ (DescriptorProto_Builder*) newBuilderWithDescriptorProto:(DescriptorProto*) prototype;
+ (DescriptorProto*) parseFromData:(NSData*) data;
+ (DescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (DescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (DescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (DescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (DescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface ExtensionRange : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional int32 start = 1;
    BOOL hasStart;
    int32_t start_;
    // optional int32 end = 2;
    BOOL hasEnd;
    int32_t end_;
}
@property BOOL hasStart;
@property int32_t start_;
@property BOOL hasEnd;
@property int32_t end_;
- (BOOL) hasStart;
- (int32_t) getStart;
- (BOOL) hasEnd;
- (int32_t) getEnd;
+ (ExtensionRange*) getDefaultInstance;
- (ExtensionRange*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (ExtensionRange_Builder*) newBuilder;
- (ExtensionRange_Builder*) newBuilderForType;
+ (ExtensionRange_Builder*) newBuilderWithExtensionRange:(ExtensionRange*) prototype;
+ (ExtensionRange*) parseFromData:(NSData*) data;
+ (ExtensionRange*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ExtensionRange*) parseFromInputStream:(NSInputStream*) input;
+ (ExtensionRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ExtensionRange*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (ExtensionRange*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface ExtensionRange_Builder : GeneratedMessage_Builder {
@private
    ExtensionRange* result;
}
@property (retain) ExtensionRange* result;
// Construct using ExtensionRange.newBuilder()
- (ExtensionRange_Builder*) clear;
- (ExtensionRange_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (ExtensionRange*) getDefaultInstanceForType;
- (ExtensionRange*) build;
- (ExtensionRange*) buildParsed;
- (ExtensionRange*) buildPartial;
- (ExtensionRange_Builder*) mergeFromMessage:(id<Message>) other;
- (ExtensionRange_Builder*) mergeFromExtensionRange:(ExtensionRange*) other;
- (ExtensionRange_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (ExtensionRange_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional int32 start = 1;
- (BOOL) hasStart;
- (int32_t) getStart;
- (ExtensionRange_Builder*) setStart:(int32_t) value;
- (ExtensionRange_Builder*) clearStart;

// optional int32 end = 2;
- (BOOL) hasEnd;
- (int32_t) getEnd;
- (ExtensionRange_Builder*) setEnd:(int32_t) value;
- (ExtensionRange_Builder*) clearEnd;
@end

@interface DescriptorProto_Builder : GeneratedMessage_Builder {
@private
    DescriptorProto* result;
}
@property (retain) DescriptorProto* result;
// Construct using DescriptorProto.newBuilder()
- (DescriptorProto_Builder*) clear;
- (DescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (DescriptorProto*) getDefaultInstanceForType;
- (DescriptorProto*) build;
- (DescriptorProto*) buildParsed;
- (DescriptorProto*) buildPartial;
- (DescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (DescriptorProto_Builder*) mergeFromDescriptorProto:(DescriptorProto*) other;
- (DescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (DescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (DescriptorProto_Builder*) setName:(NSString*) value;
- (DescriptorProto_Builder*) clearName;

// repeated .google.protobuf.FieldDescriptorProto field = 2;
- (NSArray*) getFieldList;
- (int32_t) getFieldCount;
- (FieldDescriptorProto*) getField:(int32_t) index;
- (DescriptorProto_Builder*) setField:(int32_t) index value:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) setField:(int32_t) index builderForValue:(FieldDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addFieldBuilder:(FieldDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addAllField:(NSArray*) values;
- (DescriptorProto_Builder*) clearField;
- (DescriptorProto_Builder*) addField:(FieldDescriptorProto*) value;

// repeated .google.protobuf.FieldDescriptorProto extension = 6;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (FieldDescriptorProto*) getExtension:(int32_t) index;
- (DescriptorProto_Builder*) setExtension:(int32_t) index value:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) setExtension:(int32_t) index builderForValue:(FieldDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addExtensionBuilder:(FieldDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (DescriptorProto_Builder*) clearExtension;
- (DescriptorProto_Builder*) addExtension:(FieldDescriptorProto*) value;

// repeated .google.protobuf.DescriptorProto nested_type = 3;
- (NSArray*) getNestedTypeList;
- (int32_t) getNestedTypeCount;
- (DescriptorProto*) getNestedType:(int32_t) index;
- (DescriptorProto_Builder*) setNestedType:(int32_t) index value:(DescriptorProto*) value;
- (DescriptorProto_Builder*) setNestedType:(int32_t) index builderForValue:(DescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addNestedTypeBuilder:(DescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addAllNestedType:(NSArray*) values;
- (DescriptorProto_Builder*) clearNestedType;
- (DescriptorProto_Builder*) addNestedType:(DescriptorProto*) value;

// repeated .google.protobuf.EnumDescriptorProto enum_type = 4;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (EnumDescriptorProto*) getEnumType:(int32_t) index;
- (DescriptorProto_Builder*) setEnumType:(int32_t) index value:(EnumDescriptorProto*) value;
- (DescriptorProto_Builder*) setEnumType:(int32_t) index builderForValue:(EnumDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addEnumTypeBuilder:(EnumDescriptorProto_Builder*) builderForValue;
- (DescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (DescriptorProto_Builder*) clearEnumType;
- (DescriptorProto_Builder*) addEnumType:(EnumDescriptorProto*) value;

// repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;
- (NSArray*) getExtensionRangeList;
- (int32_t) getExtensionRangeCount;
- (ExtensionRange*) getExtensionRange:(int32_t) index;
- (DescriptorProto_Builder*) setExtensionRange:(int32_t) index value:(ExtensionRange*) value;
- (DescriptorProto_Builder*) setExtensionRange:(int32_t) index builderForValue:(ExtensionRange_Builder*) builderForValue;
- (DescriptorProto_Builder*) addExtensionRangeBuilder:(ExtensionRange_Builder*) builderForValue;
- (DescriptorProto_Builder*) addAllExtensionRange:(NSArray*) values;
- (DescriptorProto_Builder*) clearExtensionRange;
- (DescriptorProto_Builder*) addExtensionRange:(ExtensionRange*) value;

// optional .google.protobuf.MessageOptions options = 7;
- (BOOL) hasOptions;
- (MessageOptions*) getOptions;
- (id<Message_Builder>) setOptions:(MessageOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(MessageOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(MessageOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface FieldDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional int32 number = 3;
    BOOL hasNumber;
    int32_t number_;
    // optional .google.protobuf.FieldDescriptorProto.Label label = 4;
    BOOL hasLabel;
    Label* label_;
    // optional .google.protobuf.FieldDescriptorProto.Type type = 5;
    BOOL hasType;
    Type* type_;
    // optional string type_name = 6;
    BOOL hasTypeName;
    NSString* typeName_;
    // optional string extendee = 2;
    BOOL hasExtendee;
    NSString* extendee_;
    // optional string default_value = 7;
    BOOL hasDefaultValue;
    NSString* defaultValue_;
    // optional .google.protobuf.FieldOptions options = 8;
    BOOL hasOptions;
    FieldOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasNumber;
@property int32_t number_;
@property BOOL hasLabel;
@property (retain) Label* label_;
@property BOOL hasType;
@property (retain) Type* type_;
@property BOOL hasTypeName;
@property (retain) NSString* typeName_;
@property BOOL hasExtendee;
@property (retain) NSString* extendee_;
@property BOOL hasDefaultValue;
@property (retain) NSString* defaultValue_;
@property BOOL hasOptions;
@property (retain) FieldOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (BOOL) hasLabel;
- (Label*) getLabel;
- (BOOL) hasType;
- (Type*) getType;
- (BOOL) hasTypeName;
- (NSString*) getTypeName;
- (BOOL) hasExtendee;
- (NSString*) getExtendee;
- (BOOL) hasDefaultValue;
- (NSString*) getDefaultValue;
- (FieldOptions*) getOptions;
+ (FieldDescriptorProto*) getDefaultInstance;
- (FieldDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (FieldDescriptorProto_Builder*) newBuilder;
- (FieldDescriptorProto_Builder*) newBuilderForType;
+ (FieldDescriptorProto_Builder*) newBuilderWithFieldDescriptorProto:(FieldDescriptorProto*) prototype;
+ (FieldDescriptorProto*) parseFromData:(NSData*) data;
+ (FieldDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (FieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FieldDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (FieldDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface Type : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (Type*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (Type*) TYPE_DOUBLE;
+ (Type*) TYPE_FLOAT;
+ (Type*) TYPE_INT64;
+ (Type*) TYPE_UINT64;
+ (Type*) TYPE_INT32;
+ (Type*) TYPE_FIXED64;
+ (Type*) TYPE_FIXED32;
+ (Type*) TYPE_BOOL_;
+ (Type*) TYPE_STRING;
+ (Type*) TYPE_GROUP;
+ (Type*) TYPE_MESSAGE;
+ (Type*) TYPE_BYTES;
+ (Type*) TYPE_UINT32;
+ (Type*) TYPE_ENUM;
+ (Type*) TYPE_SFIXED32;
+ (Type*) TYPE_SFIXED64;
+ (Type*) TYPE_SINT32;
+ (Type*) TYPE_SINT64;

- (int32_t) getNumber;
+ (Type*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (Type*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface Label : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (Label*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (Label*) LABEL_OPTIONAL;
+ (Label*) LABEL_REQUIRED;
+ (Label*) LABEL_REPEATED;

- (int32_t) getNumber;
+ (Label*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (Label*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface FieldDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    FieldDescriptorProto* result;
}
@property (retain) FieldDescriptorProto* result;
// Construct using FieldDescriptorProto.newBuilder()
- (FieldDescriptorProto_Builder*) clear;
- (FieldDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (FieldDescriptorProto*) getDefaultInstanceForType;
- (FieldDescriptorProto*) build;
- (FieldDescriptorProto*) buildParsed;
- (FieldDescriptorProto*) buildPartial;
- (FieldDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (FieldDescriptorProto_Builder*) mergeFromFieldDescriptorProto:(FieldDescriptorProto*) other;
- (FieldDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (FieldDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (FieldDescriptorProto_Builder*) setName:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearName;

// optional int32 number = 3;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (FieldDescriptorProto_Builder*) setNumber:(int32_t) value;
- (FieldDescriptorProto_Builder*) clearNumber;

// optional .google.protobuf.FieldDescriptorProto.Label label = 4;
- (BOOL) hasLabel;
- (Label*) getLabel;
- (FieldDescriptorProto_Builder*) setLabel:(Label*) value;
- (FieldDescriptorProto_Builder*) clearLabel;

// optional .google.protobuf.FieldDescriptorProto.Type type = 5;
- (BOOL) hasType;
- (Type*) getType;
- (FieldDescriptorProto_Builder*) setType:(Type*) value;
- (FieldDescriptorProto_Builder*) clearType;

// optional string type_name = 6;
- (BOOL) hasTypeName;
- (NSString*) getTypeName;
- (FieldDescriptorProto_Builder*) setTypeName:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearTypeName;

// optional string extendee = 2;
- (BOOL) hasExtendee;
- (NSString*) getExtendee;
- (FieldDescriptorProto_Builder*) setExtendee:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearExtendee;

// optional string default_value = 7;
- (BOOL) hasDefaultValue;
- (NSString*) getDefaultValue;
- (FieldDescriptorProto_Builder*) setDefaultValue:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearDefaultValue;

// optional .google.protobuf.FieldOptions options = 8;
- (BOOL) hasOptions;
- (FieldOptions*) getOptions;
- (id<Message_Builder>) setOptions:(FieldOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(FieldOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(FieldOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface EnumDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.EnumValueDescriptorProto value = 2;
    NSMutableArray* value_;
    // optional .google.protobuf.EnumOptions options = 3;
    BOOL hasOptions;
    EnumOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* value_;
@property BOOL hasOptions;
@property (retain) EnumOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getValueList;
- (int32_t) getValueCount;
- (EnumValueDescriptorProto*) getValue:(int32_t) index;
- (EnumOptions*) getOptions;
+ (EnumDescriptorProto*) getDefaultInstance;
- (EnumDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (EnumDescriptorProto_Builder*) newBuilder;
- (EnumDescriptorProto_Builder*) newBuilderForType;
+ (EnumDescriptorProto_Builder*) newBuilderWithEnumDescriptorProto:(EnumDescriptorProto*) prototype;
+ (EnumDescriptorProto*) parseFromData:(NSData*) data;
+ (EnumDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (EnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (EnumDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface EnumDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    EnumDescriptorProto* result;
}
@property (retain) EnumDescriptorProto* result;
// Construct using EnumDescriptorProto.newBuilder()
- (EnumDescriptorProto_Builder*) clear;
- (EnumDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (EnumDescriptorProto*) getDefaultInstanceForType;
- (EnumDescriptorProto*) build;
- (EnumDescriptorProto*) buildParsed;
- (EnumDescriptorProto*) buildPartial;
- (EnumDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (EnumDescriptorProto_Builder*) mergeFromEnumDescriptorProto:(EnumDescriptorProto*) other;
- (EnumDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (EnumDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (EnumDescriptorProto_Builder*) setName:(NSString*) value;
- (EnumDescriptorProto_Builder*) clearName;

// repeated .google.protobuf.EnumValueDescriptorProto value = 2;
- (NSArray*) getValueList;
- (int32_t) getValueCount;
- (EnumValueDescriptorProto*) getValue:(int32_t) index;
- (EnumDescriptorProto_Builder*) setValue:(int32_t) index value:(EnumValueDescriptorProto*) value;
- (EnumDescriptorProto_Builder*) setValue:(int32_t) index builderForValue:(EnumValueDescriptorProto_Builder*) builderForValue;
- (EnumDescriptorProto_Builder*) addValueBuilder:(EnumValueDescriptorProto_Builder*) builderForValue;
- (EnumDescriptorProto_Builder*) addAllValue:(NSArray*) values;
- (EnumDescriptorProto_Builder*) clearValue;
- (EnumDescriptorProto_Builder*) addValue:(EnumValueDescriptorProto*) value;

// optional .google.protobuf.EnumOptions options = 3;
- (BOOL) hasOptions;
- (EnumOptions*) getOptions;
- (id<Message_Builder>) setOptions:(EnumOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(EnumOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(EnumOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface EnumValueDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional int32 number = 2;
    BOOL hasNumber;
    int32_t number_;
    // optional .google.protobuf.EnumValueOptions options = 3;
    BOOL hasOptions;
    EnumValueOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasNumber;
@property int32_t number_;
@property BOOL hasOptions;
@property (retain) EnumValueOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (EnumValueOptions*) getOptions;
+ (EnumValueDescriptorProto*) getDefaultInstance;
- (EnumValueDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (EnumValueDescriptorProto_Builder*) newBuilder;
- (EnumValueDescriptorProto_Builder*) newBuilderForType;
+ (EnumValueDescriptorProto_Builder*) newBuilderWithEnumValueDescriptorProto:(EnumValueDescriptorProto*) prototype;
+ (EnumValueDescriptorProto*) parseFromData:(NSData*) data;
+ (EnumValueDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (EnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumValueDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (EnumValueDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    EnumValueDescriptorProto* result;
}
@property (retain) EnumValueDescriptorProto* result;
// Construct using EnumValueDescriptorProto.newBuilder()
- (EnumValueDescriptorProto_Builder*) clear;
- (EnumValueDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (EnumValueDescriptorProto*) getDefaultInstanceForType;
- (EnumValueDescriptorProto*) build;
- (EnumValueDescriptorProto*) buildParsed;
- (EnumValueDescriptorProto*) buildPartial;
- (EnumValueDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (EnumValueDescriptorProto_Builder*) mergeFromEnumValueDescriptorProto:(EnumValueDescriptorProto*) other;
- (EnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (EnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (EnumValueDescriptorProto_Builder*) setName:(NSString*) value;
- (EnumValueDescriptorProto_Builder*) clearName;

// optional int32 number = 2;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (EnumValueDescriptorProto_Builder*) setNumber:(int32_t) value;
- (EnumValueDescriptorProto_Builder*) clearNumber;

// optional .google.protobuf.EnumValueOptions options = 3;
- (BOOL) hasOptions;
- (EnumValueOptions*) getOptions;
- (id<Message_Builder>) setOptions:(EnumValueOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(EnumValueOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(EnumValueOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface ServiceDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.MethodDescriptorProto method = 2;
    NSMutableArray* method_;
    // optional .google.protobuf.ServiceOptions options = 3;
    BOOL hasOptions;
    ServiceOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* method_;
@property BOOL hasOptions;
@property (retain) ServiceOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getMethodList;
- (int32_t) getMethodCount;
- (MethodDescriptorProto*) getMethod:(int32_t) index;
- (ServiceOptions*) getOptions;
+ (ServiceDescriptorProto*) getDefaultInstance;
- (ServiceDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (ServiceDescriptorProto_Builder*) newBuilder;
- (ServiceDescriptorProto_Builder*) newBuilderForType;
+ (ServiceDescriptorProto_Builder*) newBuilderWithServiceDescriptorProto:(ServiceDescriptorProto*) prototype;
+ (ServiceDescriptorProto*) parseFromData:(NSData*) data;
+ (ServiceDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (ServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ServiceDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (ServiceDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface ServiceDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    ServiceDescriptorProto* result;
}
@property (retain) ServiceDescriptorProto* result;
// Construct using ServiceDescriptorProto.newBuilder()
- (ServiceDescriptorProto_Builder*) clear;
- (ServiceDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (ServiceDescriptorProto*) getDefaultInstanceForType;
- (ServiceDescriptorProto*) build;
- (ServiceDescriptorProto*) buildParsed;
- (ServiceDescriptorProto*) buildPartial;
- (ServiceDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (ServiceDescriptorProto_Builder*) mergeFromServiceDescriptorProto:(ServiceDescriptorProto*) other;
- (ServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (ServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (ServiceDescriptorProto_Builder*) setName:(NSString*) value;
- (ServiceDescriptorProto_Builder*) clearName;

// repeated .google.protobuf.MethodDescriptorProto method = 2;
- (NSArray*) getMethodList;
- (int32_t) getMethodCount;
- (MethodDescriptorProto*) getMethod:(int32_t) index;
- (ServiceDescriptorProto_Builder*) setMethod:(int32_t) index value:(MethodDescriptorProto*) value;
- (ServiceDescriptorProto_Builder*) setMethod:(int32_t) index builderForValue:(MethodDescriptorProto_Builder*) builderForValue;
- (ServiceDescriptorProto_Builder*) addMethodBuilder:(MethodDescriptorProto_Builder*) builderForValue;
- (ServiceDescriptorProto_Builder*) addAllMethod:(NSArray*) values;
- (ServiceDescriptorProto_Builder*) clearMethod;
- (ServiceDescriptorProto_Builder*) addMethod:(MethodDescriptorProto*) value;

// optional .google.protobuf.ServiceOptions options = 3;
- (BOOL) hasOptions;
- (ServiceOptions*) getOptions;
- (id<Message_Builder>) setOptions:(ServiceOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(ServiceOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(ServiceOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface MethodDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional string input_type = 2;
    BOOL hasInputType;
    NSString* inputType_;
    // optional string output_type = 3;
    BOOL hasOutputType;
    NSString* outputType_;
    // optional .google.protobuf.MethodOptions options = 4;
    BOOL hasOptions;
    MethodOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasInputType;
@property (retain) NSString* inputType_;
@property BOOL hasOutputType;
@property (retain) NSString* outputType_;
@property BOOL hasOptions;
@property (retain) MethodOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasInputType;
- (NSString*) getInputType;
- (BOOL) hasOutputType;
- (NSString*) getOutputType;
- (MethodOptions*) getOptions;
+ (MethodDescriptorProto*) getDefaultInstance;
- (MethodDescriptorProto*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (MethodDescriptorProto_Builder*) newBuilder;
- (MethodDescriptorProto_Builder*) newBuilderForType;
+ (MethodDescriptorProto_Builder*) newBuilderWithMethodDescriptorProto:(MethodDescriptorProto*) prototype;
+ (MethodDescriptorProto*) parseFromData:(NSData*) data;
+ (MethodDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (MethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MethodDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (MethodDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface MethodDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    MethodDescriptorProto* result;
}
@property (retain) MethodDescriptorProto* result;
// Construct using MethodDescriptorProto.newBuilder()
- (MethodDescriptorProto_Builder*) clear;
- (MethodDescriptorProto_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (MethodDescriptorProto*) getDefaultInstanceForType;
- (MethodDescriptorProto*) build;
- (MethodDescriptorProto*) buildParsed;
- (MethodDescriptorProto*) buildPartial;
- (MethodDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (MethodDescriptorProto_Builder*) mergeFromMethodDescriptorProto:(MethodDescriptorProto*) other;
- (MethodDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (MethodDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (MethodDescriptorProto_Builder*) setName:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearName;

// optional string input_type = 2;
- (BOOL) hasInputType;
- (NSString*) getInputType;
- (MethodDescriptorProto_Builder*) setInputType:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearInputType;

// optional string output_type = 3;
- (BOOL) hasOutputType;
- (NSString*) getOutputType;
- (MethodDescriptorProto_Builder*) setOutputType:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearOutputType;

// optional .google.protobuf.MethodOptions options = 4;
- (BOOL) hasOptions;
- (MethodOptions*) getOptions;
- (id<Message_Builder>) setOptions:(MethodOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(MethodOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(MethodOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface FileOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string java_package = 1;
    BOOL hasJavaPackage;
    NSString* javaPackage_;
    // optional string java_outer_classname = 8;
    BOOL hasJavaOuterClassname;
    NSString* javaOuterClassname_;
    // optional bool java_multiple_files = 10 [default = false];
    BOOL hasJavaMultipleFiles;
    BOOL javaMultipleFiles_;
    // optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = CODE_SIZE];
    BOOL hasOptimizeFor;
    OptimizeMode* optimizeFor_;
    // optional string objectivec_namespace = 11;
    BOOL hasObjectivecNamespace;
    NSString* objectivecNamespace_;
}
@property BOOL hasJavaPackage;
@property (retain) NSString* javaPackage_;
@property BOOL hasJavaOuterClassname;
@property (retain) NSString* javaOuterClassname_;
@property BOOL hasJavaMultipleFiles;
@property BOOL javaMultipleFiles_;
@property BOOL hasOptimizeFor;
@property (retain) OptimizeMode* optimizeFor_;
@property BOOL hasObjectivecNamespace;
@property (retain) NSString* objectivecNamespace_;
- (BOOL) hasJavaPackage;
- (NSString*) getJavaPackage;
- (BOOL) hasJavaOuterClassname;
- (NSString*) getJavaOuterClassname;
- (BOOL) hasJavaMultipleFiles;
- (BOOL) getJavaMultipleFiles;
- (BOOL) hasOptimizeFor;
- (OptimizeMode*) getOptimizeFor;
- (BOOL) hasObjectivecNamespace;
- (NSString*) getObjectivecNamespace;
+ (FileOptions*) getDefaultInstance;
- (FileOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (FileOptions_Builder*) newBuilder;
- (FileOptions_Builder*) newBuilderForType;
+ (FileOptions_Builder*) newBuilderWithFileOptions:(FileOptions*) prototype;
+ (FileOptions*) parseFromData:(NSData*) data;
+ (FileOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (FileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FileOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (FileOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface OptimizeMode : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (OptimizeMode*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (OptimizeMode*) SPEED;
+ (OptimizeMode*) CODE_SIZE;

- (int32_t) getNumber;
+ (OptimizeMode*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (OptimizeMode*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface FileOptions_Builder : GeneratedMessage_Builder {
@private
    FileOptions* result;
}
@property (retain) FileOptions* result;
// Construct using FileOptions.newBuilder()
- (FileOptions_Builder*) clear;
- (FileOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (FileOptions*) getDefaultInstanceForType;
- (FileOptions*) build;
- (FileOptions*) buildParsed;
- (FileOptions*) buildPartial;
- (FileOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (FileOptions_Builder*) mergeFromFileOptions:(FileOptions*) other;
- (FileOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (FileOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string java_package = 1;
- (BOOL) hasJavaPackage;
- (NSString*) getJavaPackage;
- (FileOptions_Builder*) setJavaPackage:(NSString*) value;
- (FileOptions_Builder*) clearJavaPackage;

// optional string java_outer_classname = 8;
- (BOOL) hasJavaOuterClassname;
- (NSString*) getJavaOuterClassname;
- (FileOptions_Builder*) setJavaOuterClassname:(NSString*) value;
- (FileOptions_Builder*) clearJavaOuterClassname;

// optional bool java_multiple_files = 10 [default = false];
- (BOOL) hasJavaMultipleFiles;
- (BOOL) getJavaMultipleFiles;
- (FileOptions_Builder*) setJavaMultipleFiles:(BOOL) value;
- (FileOptions_Builder*) clearJavaMultipleFiles;

// optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = CODE_SIZE];
- (BOOL) hasOptimizeFor;
- (OptimizeMode*) getOptimizeFor;
- (FileOptions_Builder*) setOptimizeFor:(OptimizeMode*) value;
- (FileOptions_Builder*) clearOptimizeFor;

// optional string objectivec_namespace = 11;
- (BOOL) hasObjectivecNamespace;
- (NSString*) getObjectivecNamespace;
- (FileOptions_Builder*) setObjectivecNamespace:(NSString*) value;
- (FileOptions_Builder*) clearObjectivecNamespace;
@end

@interface MessageOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional bool message_set_wire_format = 1 [default = false];
    BOOL hasMessageSetWireFormat;
    BOOL messageSetWireFormat_;
}
@property BOOL hasMessageSetWireFormat;
@property BOOL messageSetWireFormat_;
- (BOOL) hasMessageSetWireFormat;
- (BOOL) getMessageSetWireFormat;
+ (MessageOptions*) getDefaultInstance;
- (MessageOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (MessageOptions_Builder*) newBuilder;
- (MessageOptions_Builder*) newBuilderForType;
+ (MessageOptions_Builder*) newBuilderWithMessageOptions:(MessageOptions*) prototype;
+ (MessageOptions*) parseFromData:(NSData*) data;
+ (MessageOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MessageOptions*) parseFromInputStream:(NSInputStream*) input;
+ (MessageOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MessageOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (MessageOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface MessageOptions_Builder : GeneratedMessage_Builder {
@private
    MessageOptions* result;
}
@property (retain) MessageOptions* result;
// Construct using MessageOptions.newBuilder()
- (MessageOptions_Builder*) clear;
- (MessageOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (MessageOptions*) getDefaultInstanceForType;
- (MessageOptions*) build;
- (MessageOptions*) buildParsed;
- (MessageOptions*) buildPartial;
- (MessageOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (MessageOptions_Builder*) mergeFromMessageOptions:(MessageOptions*) other;
- (MessageOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (MessageOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional bool message_set_wire_format = 1 [default = false];
- (BOOL) hasMessageSetWireFormat;
- (BOOL) getMessageSetWireFormat;
- (MessageOptions_Builder*) setMessageSetWireFormat:(BOOL) value;
- (MessageOptions_Builder*) clearMessageSetWireFormat;
@end

@interface FieldOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional .google.protobuf.FieldOptions.CType ctype = 1;
    BOOL hasCtype;
    CType* ctype_;
    // optional string experimental_map_key = 9;
    BOOL hasExperimentalMapKey;
    NSString* experimentalMapKey_;
}
@property BOOL hasCtype;
@property (retain) CType* ctype_;
@property BOOL hasExperimentalMapKey;
@property (retain) NSString* experimentalMapKey_;
- (BOOL) hasCtype;
- (CType*) getCtype;
- (BOOL) hasExperimentalMapKey;
- (NSString*) getExperimentalMapKey;
+ (FieldOptions*) getDefaultInstance;
- (FieldOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (FieldOptions_Builder*) newBuilder;
- (FieldOptions_Builder*) newBuilderForType;
+ (FieldOptions_Builder*) newBuilderWithFieldOptions:(FieldOptions*) prototype;
+ (FieldOptions*) parseFromData:(NSData*) data;
+ (FieldOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FieldOptions*) parseFromInputStream:(NSInputStream*) input;
+ (FieldOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (FieldOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (FieldOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface CType : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (CType*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (CType*) CORD;
+ (CType*) STRING_PIECE;

- (int32_t) getNumber;
+ (CType*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (CType*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface FieldOptions_Builder : GeneratedMessage_Builder {
@private
    FieldOptions* result;
}
@property (retain) FieldOptions* result;
// Construct using FieldOptions.newBuilder()
- (FieldOptions_Builder*) clear;
- (FieldOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (FieldOptions*) getDefaultInstanceForType;
- (FieldOptions*) build;
- (FieldOptions*) buildParsed;
- (FieldOptions*) buildPartial;
- (FieldOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (FieldOptions_Builder*) mergeFromFieldOptions:(FieldOptions*) other;
- (FieldOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (FieldOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional .google.protobuf.FieldOptions.CType ctype = 1;
- (BOOL) hasCtype;
- (CType*) getCtype;
- (FieldOptions_Builder*) setCtype:(CType*) value;
- (FieldOptions_Builder*) clearCtype;

// optional string experimental_map_key = 9;
- (BOOL) hasExperimentalMapKey;
- (NSString*) getExperimentalMapKey;
- (FieldOptions_Builder*) setExperimentalMapKey:(NSString*) value;
- (FieldOptions_Builder*) clearExperimentalMapKey;
@end

@interface EnumOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (EnumOptions*) getDefaultInstance;
- (EnumOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (EnumOptions_Builder*) newBuilder;
- (EnumOptions_Builder*) newBuilderForType;
+ (EnumOptions_Builder*) newBuilderWithEnumOptions:(EnumOptions*) prototype;
+ (EnumOptions*) parseFromData:(NSData*) data;
+ (EnumOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumOptions*) parseFromInputStream:(NSInputStream*) input;
+ (EnumOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (EnumOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface EnumOptions_Builder : GeneratedMessage_Builder {
@private
    EnumOptions* result;
}
@property (retain) EnumOptions* result;
// Construct using EnumOptions.newBuilder()
- (EnumOptions_Builder*) clear;
- (EnumOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (EnumOptions*) getDefaultInstanceForType;
- (EnumOptions*) build;
- (EnumOptions*) buildParsed;
- (EnumOptions*) buildPartial;
- (EnumOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (EnumOptions_Builder*) mergeFromEnumOptions:(EnumOptions*) other;
- (EnumOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (EnumOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (EnumValueOptions*) getDefaultInstance;
- (EnumValueOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (EnumValueOptions_Builder*) newBuilder;
- (EnumValueOptions_Builder*) newBuilderForType;
+ (EnumValueOptions_Builder*) newBuilderWithEnumValueOptions:(EnumValueOptions*) prototype;
+ (EnumValueOptions*) parseFromData:(NSData*) data;
+ (EnumValueOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumValueOptions*) parseFromInputStream:(NSInputStream*) input;
+ (EnumValueOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (EnumValueOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (EnumValueOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueOptions_Builder : GeneratedMessage_Builder {
@private
    EnumValueOptions* result;
}
@property (retain) EnumValueOptions* result;
// Construct using EnumValueOptions.newBuilder()
- (EnumValueOptions_Builder*) clear;
- (EnumValueOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (EnumValueOptions*) getDefaultInstanceForType;
- (EnumValueOptions*) build;
- (EnumValueOptions*) buildParsed;
- (EnumValueOptions*) buildPartial;
- (EnumValueOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (EnumValueOptions_Builder*) mergeFromEnumValueOptions:(EnumValueOptions*) other;
- (EnumValueOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (EnumValueOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface ServiceOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (ServiceOptions*) getDefaultInstance;
- (ServiceOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (ServiceOptions_Builder*) newBuilder;
- (ServiceOptions_Builder*) newBuilderForType;
+ (ServiceOptions_Builder*) newBuilderWithServiceOptions:(ServiceOptions*) prototype;
+ (ServiceOptions*) parseFromData:(NSData*) data;
+ (ServiceOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ServiceOptions*) parseFromInputStream:(NSInputStream*) input;
+ (ServiceOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (ServiceOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (ServiceOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface ServiceOptions_Builder : GeneratedMessage_Builder {
@private
    ServiceOptions* result;
}
@property (retain) ServiceOptions* result;
// Construct using ServiceOptions.newBuilder()
- (ServiceOptions_Builder*) clear;
- (ServiceOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (ServiceOptions*) getDefaultInstanceForType;
- (ServiceOptions*) build;
- (ServiceOptions*) buildParsed;
- (ServiceOptions*) buildPartial;
- (ServiceOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (ServiceOptions_Builder*) mergeFromServiceOptions:(ServiceOptions*) other;
- (ServiceOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (ServiceOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface MethodOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (MethodOptions*) getDefaultInstance;
- (MethodOptions*) getDefaultInstanceForType;
+ (ProtocolBufferDescriptor*) getDescriptor;
- (GeneratedMessage_FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (MethodOptions_Builder*) newBuilder;
- (MethodOptions_Builder*) newBuilderForType;
+ (MethodOptions_Builder*) newBuilderWithMethodOptions:(MethodOptions*) prototype;
+ (MethodOptions*) parseFromData:(NSData*) data;
+ (MethodOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MethodOptions*) parseFromInputStream:(NSInputStream*) input;
+ (MethodOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (MethodOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (MethodOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface MethodOptions_Builder : GeneratedMessage_Builder {
@private
    MethodOptions* result;
}
@property (retain) MethodOptions* result;
// Construct using MethodOptions.newBuilder()
- (MethodOptions_Builder*) clear;
- (MethodOptions_Builder*) clone;
- (ProtocolBufferDescriptor*) getDescriptorForType;
- (MethodOptions*) getDefaultInstanceForType;
- (MethodOptions*) build;
- (MethodOptions*) buildParsed;
- (MethodOptions*) buildPartial;
- (MethodOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (MethodOptions_Builder*) mergeFromMethodOptions:(MethodOptions*) other;
- (MethodOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (MethodOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

