// Generated by the protocol buffer compiler.  DO NOT EDIT!

@class FieldAccessorTable;
@class GeneratedMessage_Builder;
@class PBCType;
@class PBDescriptorProto;
@class PBDescriptorProto_Builder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProto_Builder;
@class PBEnumOptions;
@class PBEnumOptions_Builder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProto_Builder;
@class PBEnumValueOptions;
@class PBEnumValueOptions_Builder;
@class PBExtensionRange;
@class PBExtensionRange_Builder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProto_Builder;
@class PBFieldOptions;
@class PBFieldOptions_Builder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProto_Builder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSet_Builder;
@class PBFileOptions;
@class PBFileOptions_Builder;
@class PBLabel;
@class PBMessageOptions;
@class PBMessageOptions_Builder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProto_Builder;
@class PBMethodOptions;
@class PBMethodOptions_Builder;
@class PBOptimizeMode;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProto_Builder;
@class PBServiceOptions;
@class PBServiceOptions_Builder;
@class PBType;

@interface DescriptorProtoRoot : NSObject {
}
+ (FileDescriptor*) getDescriptor;
+ (FileDescriptor*) buildDescriptor;
+ (Descriptor*) internal_static_google_protobuf_FileDescriptorSet_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_FileDescriptorSet_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_FileDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_FileDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_DescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_DescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_DescriptorProto_ExtensionRange_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_DescriptorProto_ExtensionRange_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_FieldDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_FieldDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_EnumDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_EnumDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_EnumValueDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_EnumValueDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_ServiceDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_ServiceDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_MethodDescriptorProto_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_MethodDescriptorProto_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_FileOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_FileOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_MessageOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_MessageOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_FieldOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_FieldOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_EnumOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_EnumOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_EnumValueOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_EnumValueOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_ServiceOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_ServiceOptions_fieldAccessorTable;
+ (Descriptor*) internal_static_google_protobuf_MethodOptions_descriptor;
+ (FieldAccessorTable*) internal_static_google_protobuf_MethodOptions_fieldAccessorTable;
@end

@interface PBFileDescriptorSet : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // repeated .google.protobuf.FileDescriptorProto file = 1;
    NSMutableArray* file_;
}
@property (retain) NSMutableArray* file_;
- (NSArray*) getFileList;
- (int32_t) getFileCount;
- (PBFileDescriptorProto*) getFile:(int32_t) index;
+ (PBFileDescriptorSet*) getDefaultInstance;
- (PBFileDescriptorSet*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBFileDescriptorSet_Builder*) newBuilder;
- (PBFileDescriptorSet_Builder*) newBuilderForType;
+ (PBFileDescriptorSet_Builder*) newBuilderWithPBFileDescriptorSet:(PBFileDescriptorSet*) prototype;
+ (PBFileDescriptorSet*) parseFromData:(NSData*) data;
+ (PBFileDescriptorSet*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorSet*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBFileDescriptorSet*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBFileDescriptorSet_Builder : GeneratedMessage_Builder {
@private
    PBFileDescriptorSet* result;
}
@property (retain) PBFileDescriptorSet* result;
// Construct using PBFileDescriptorSet.newBuilder()
- (PBFileDescriptorSet_Builder*) clear;
- (PBFileDescriptorSet_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBFileDescriptorSet*) getDefaultInstanceForType;
- (PBFileDescriptorSet*) build;
- (PBFileDescriptorSet*) buildParsed;
- (PBFileDescriptorSet*) buildPartial;
- (PBFileDescriptorSet_Builder*) mergeFromMessage:(id<Message>) other;
- (PBFileDescriptorSet_Builder*) mergeFromPBFileDescriptorSet:(PBFileDescriptorSet*) other;
- (PBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// repeated .google.protobuf.FileDescriptorProto file = 1;
- (NSArray*) getFileList;
- (int32_t) getFileCount;
- (PBFileDescriptorProto*) getFile:(int32_t) index;
- (PBFileDescriptorSet_Builder*) setFile:(int32_t) index value:(PBFileDescriptorProto*) value;
- (PBFileDescriptorSet_Builder*) setFile:(int32_t) index builderForValue:(PBFileDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorSet_Builder*) addFileBuilder:(PBFileDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorSet_Builder*) addAllFile:(NSArray*) values;
- (PBFileDescriptorSet_Builder*) clearFile;
- (PBFileDescriptorSet_Builder*) addFile:(PBFileDescriptorProto*) value;
@end

@interface PBFileDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional string package = 2;
    BOOL hasPackage;
    NSString* package_;
    // repeated string dependency = 3;
    NSMutableArray* dependency_;
    // repeated .google.protobuf.DescriptorProto message_type = 4;
    NSMutableArray* messageType_;
    // repeated .google.protobuf.EnumDescriptorProto enum_type = 5;
    NSMutableArray* enumType_;
    // repeated .google.protobuf.ServiceDescriptorProto service = 6;
    NSMutableArray* service_;
    // repeated .google.protobuf.FieldDescriptorProto extension = 7;
    NSMutableArray* extension_;
    // optional .google.protobuf.FileOptions options = 8;
    BOOL hasOptions;
    PBFileOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasPackage;
@property (retain) NSString* package_;
@property (retain) NSMutableArray* dependency_;
@property (retain) NSMutableArray* messageType_;
@property (retain) NSMutableArray* enumType_;
@property (retain) NSMutableArray* service_;
@property (retain) NSMutableArray* extension_;
@property BOOL hasOptions;
@property (retain) PBFileOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasPackage;
- (NSString*) getPackage;
- (NSArray*) getDependencyList;
- (int32_t) getDependencyCount;
- (NSString*) getDependency:(int32_t) index;
- (NSArray*) getMessageTypeList;
- (int32_t) getMessageTypeCount;
- (PBDescriptorProto*) getMessageType:(int32_t) index;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (PBEnumDescriptorProto*) getEnumType:(int32_t) index;
- (NSArray*) getServiceList;
- (int32_t) getServiceCount;
- (PBServiceDescriptorProto*) getService:(int32_t) index;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (PBFieldDescriptorProto*) getExtension:(int32_t) index;
- (PBFileOptions*) getOptions;
+ (PBFileDescriptorProto*) getDefaultInstance;
- (PBFileDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBFileDescriptorProto_Builder*) newBuilder;
- (PBFileDescriptorProto_Builder*) newBuilderForType;
+ (PBFileDescriptorProto_Builder*) newBuilderWithPBFileDescriptorProto:(PBFileDescriptorProto*) prototype;
+ (PBFileDescriptorProto*) parseFromData:(NSData*) data;
+ (PBFileDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBFileDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBFileDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBFileDescriptorProto* result;
}
@property (retain) PBFileDescriptorProto* result;
// Construct using PBFileDescriptorProto.newBuilder()
- (PBFileDescriptorProto_Builder*) clear;
- (PBFileDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBFileDescriptorProto*) getDefaultInstanceForType;
- (PBFileDescriptorProto*) build;
- (PBFileDescriptorProto*) buildParsed;
- (PBFileDescriptorProto*) buildPartial;
- (PBFileDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBFileDescriptorProto_Builder*) mergeFromPBFileDescriptorProto:(PBFileDescriptorProto*) other;
- (PBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBFileDescriptorProto_Builder*) setName:(NSString*) value;
- (PBFileDescriptorProto_Builder*) clearName;

// optional string package = 2;
- (BOOL) hasPackage;
- (NSString*) getPackage;
- (PBFileDescriptorProto_Builder*) setPackage:(NSString*) value;
- (PBFileDescriptorProto_Builder*) clearPackage;

// repeated string dependency = 3;
- (NSArray*) getDependencyList;
- (int32_t) getDependencyCount;
- (NSString*) getDependency:(int32_t) index;
- (PBFileDescriptorProto_Builder*) setDependency:(int32_t) index value:(NSString*) value;
- (PBFileDescriptorProto_Builder*) addDependency:(NSString*) value;
- (PBFileDescriptorProto_Builder*) addAllDependency:(NSArray*) values;
- (PBFileDescriptorProto_Builder*) clearDependency;

// repeated .google.protobuf.DescriptorProto message_type = 4;
- (NSArray*) getMessageTypeList;
- (int32_t) getMessageTypeCount;
- (PBDescriptorProto*) getMessageType:(int32_t) index;
- (PBFileDescriptorProto_Builder*) setMessageType:(int32_t) index value:(PBDescriptorProto*) value;
- (PBFileDescriptorProto_Builder*) setMessageType:(int32_t) index builderForValue:(PBDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addMessageTypeBuilder:(PBDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addAllMessageType:(NSArray*) values;
- (PBFileDescriptorProto_Builder*) clearMessageType;
- (PBFileDescriptorProto_Builder*) addMessageType:(PBDescriptorProto*) value;

// repeated .google.protobuf.EnumDescriptorProto enum_type = 5;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (PBEnumDescriptorProto*) getEnumType:(int32_t) index;
- (PBFileDescriptorProto_Builder*) setEnumType:(int32_t) index value:(PBEnumDescriptorProto*) value;
- (PBFileDescriptorProto_Builder*) setEnumType:(int32_t) index builderForValue:(PBEnumDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addEnumTypeBuilder:(PBEnumDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (PBFileDescriptorProto_Builder*) clearEnumType;
- (PBFileDescriptorProto_Builder*) addEnumType:(PBEnumDescriptorProto*) value;

// repeated .google.protobuf.ServiceDescriptorProto service = 6;
- (NSArray*) getServiceList;
- (int32_t) getServiceCount;
- (PBServiceDescriptorProto*) getService:(int32_t) index;
- (PBFileDescriptorProto_Builder*) setService:(int32_t) index value:(PBServiceDescriptorProto*) value;
- (PBFileDescriptorProto_Builder*) setService:(int32_t) index builderForValue:(PBServiceDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addServiceBuilder:(PBServiceDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addAllService:(NSArray*) values;
- (PBFileDescriptorProto_Builder*) clearService;
- (PBFileDescriptorProto_Builder*) addService:(PBServiceDescriptorProto*) value;

// repeated .google.protobuf.FieldDescriptorProto extension = 7;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (PBFieldDescriptorProto*) getExtension:(int32_t) index;
- (PBFileDescriptorProto_Builder*) setExtension:(int32_t) index value:(PBFieldDescriptorProto*) value;
- (PBFileDescriptorProto_Builder*) setExtension:(int32_t) index builderForValue:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addExtensionBuilder:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBFileDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (PBFileDescriptorProto_Builder*) clearExtension;
- (PBFileDescriptorProto_Builder*) addExtension:(PBFieldDescriptorProto*) value;

// optional .google.protobuf.FileOptions options = 8;
- (BOOL) hasOptions;
- (PBFileOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBFileOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBFileOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBFileOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.FieldDescriptorProto field = 2;
    NSMutableArray* field_;
    // repeated .google.protobuf.FieldDescriptorProto extension = 6;
    NSMutableArray* extension_;
    // repeated .google.protobuf.DescriptorProto nested_type = 3;
    NSMutableArray* nestedType_;
    // repeated .google.protobuf.EnumDescriptorProto enum_type = 4;
    NSMutableArray* enumType_;
    // repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;
    NSMutableArray* extensionRange_;
    // optional .google.protobuf.MessageOptions options = 7;
    BOOL hasOptions;
    PBMessageOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* field_;
@property (retain) NSMutableArray* extension_;
@property (retain) NSMutableArray* nestedType_;
@property (retain) NSMutableArray* enumType_;
@property (retain) NSMutableArray* extensionRange_;
@property BOOL hasOptions;
@property (retain) PBMessageOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getFieldList;
- (int32_t) getFieldCount;
- (PBFieldDescriptorProto*) getField:(int32_t) index;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (PBFieldDescriptorProto*) getExtension:(int32_t) index;
- (NSArray*) getNestedTypeList;
- (int32_t) getNestedTypeCount;
- (PBDescriptorProto*) getNestedType:(int32_t) index;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (PBEnumDescriptorProto*) getEnumType:(int32_t) index;
- (NSArray*) getExtensionRangeList;
- (int32_t) getExtensionRangeCount;
- (PBExtensionRange*) getExtensionRange:(int32_t) index;
- (PBMessageOptions*) getOptions;
+ (PBDescriptorProto*) getDefaultInstance;
- (PBDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBDescriptorProto_Builder*) newBuilder;
- (PBDescriptorProto_Builder*) newBuilderForType;
+ (PBDescriptorProto_Builder*) newBuilderWithPBDescriptorProto:(PBDescriptorProto*) prototype;
+ (PBDescriptorProto*) parseFromData:(NSData*) data;
+ (PBDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBExtensionRange : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional int32 start = 1;
    BOOL hasStart;
    int32_t start_;
    // optional int32 end = 2;
    BOOL hasEnd;
    int32_t end_;
}
@property BOOL hasStart;
@property int32_t start_;
@property BOOL hasEnd;
@property int32_t end_;
- (BOOL) hasStart;
- (int32_t) getStart;
- (BOOL) hasEnd;
- (int32_t) getEnd;
+ (PBExtensionRange*) getDefaultInstance;
- (PBExtensionRange*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBExtensionRange_Builder*) newBuilder;
- (PBExtensionRange_Builder*) newBuilderForType;
+ (PBExtensionRange_Builder*) newBuilderWithPBExtensionRange:(PBExtensionRange*) prototype;
+ (PBExtensionRange*) parseFromData:(NSData*) data;
+ (PBExtensionRange*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBExtensionRange*) parseFromInputStream:(NSInputStream*) input;
+ (PBExtensionRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBExtensionRange*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBExtensionRange*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBExtensionRange_Builder : GeneratedMessage_Builder {
@private
    PBExtensionRange* result;
}
@property (retain) PBExtensionRange* result;
// Construct using PBExtensionRange.newBuilder()
- (PBExtensionRange_Builder*) clear;
- (PBExtensionRange_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBExtensionRange*) getDefaultInstanceForType;
- (PBExtensionRange*) build;
- (PBExtensionRange*) buildParsed;
- (PBExtensionRange*) buildPartial;
- (PBExtensionRange_Builder*) mergeFromMessage:(id<Message>) other;
- (PBExtensionRange_Builder*) mergeFromPBExtensionRange:(PBExtensionRange*) other;
- (PBExtensionRange_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBExtensionRange_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional int32 start = 1;
- (BOOL) hasStart;
- (int32_t) getStart;
- (PBExtensionRange_Builder*) setStart:(int32_t) value;
- (PBExtensionRange_Builder*) clearStart;

// optional int32 end = 2;
- (BOOL) hasEnd;
- (int32_t) getEnd;
- (PBExtensionRange_Builder*) setEnd:(int32_t) value;
- (PBExtensionRange_Builder*) clearEnd;
@end

@interface PBDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBDescriptorProto* result;
}
@property (retain) PBDescriptorProto* result;
// Construct using PBDescriptorProto.newBuilder()
- (PBDescriptorProto_Builder*) clear;
- (PBDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBDescriptorProto*) getDefaultInstanceForType;
- (PBDescriptorProto*) build;
- (PBDescriptorProto*) buildParsed;
- (PBDescriptorProto*) buildPartial;
- (PBDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBDescriptorProto_Builder*) mergeFromPBDescriptorProto:(PBDescriptorProto*) other;
- (PBDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBDescriptorProto_Builder*) setName:(NSString*) value;
- (PBDescriptorProto_Builder*) clearName;

// repeated .google.protobuf.FieldDescriptorProto field = 2;
- (NSArray*) getFieldList;
- (int32_t) getFieldCount;
- (PBFieldDescriptorProto*) getField:(int32_t) index;
- (PBDescriptorProto_Builder*) setField:(int32_t) index value:(PBFieldDescriptorProto*) value;
- (PBDescriptorProto_Builder*) setField:(int32_t) index builderForValue:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addFieldBuilder:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addAllField:(NSArray*) values;
- (PBDescriptorProto_Builder*) clearField;
- (PBDescriptorProto_Builder*) addField:(PBFieldDescriptorProto*) value;

// repeated .google.protobuf.FieldDescriptorProto extension = 6;
- (NSArray*) getExtensionList;
- (int32_t) getExtensionCount;
- (PBFieldDescriptorProto*) getExtension:(int32_t) index;
- (PBDescriptorProto_Builder*) setExtension:(int32_t) index value:(PBFieldDescriptorProto*) value;
- (PBDescriptorProto_Builder*) setExtension:(int32_t) index builderForValue:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addExtensionBuilder:(PBFieldDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (PBDescriptorProto_Builder*) clearExtension;
- (PBDescriptorProto_Builder*) addExtension:(PBFieldDescriptorProto*) value;

// repeated .google.protobuf.DescriptorProto nested_type = 3;
- (NSArray*) getNestedTypeList;
- (int32_t) getNestedTypeCount;
- (PBDescriptorProto*) getNestedType:(int32_t) index;
- (PBDescriptorProto_Builder*) setNestedType:(int32_t) index value:(PBDescriptorProto*) value;
- (PBDescriptorProto_Builder*) setNestedType:(int32_t) index builderForValue:(PBDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addNestedTypeBuilder:(PBDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addAllNestedType:(NSArray*) values;
- (PBDescriptorProto_Builder*) clearNestedType;
- (PBDescriptorProto_Builder*) addNestedType:(PBDescriptorProto*) value;

// repeated .google.protobuf.EnumDescriptorProto enum_type = 4;
- (NSArray*) getEnumTypeList;
- (int32_t) getEnumTypeCount;
- (PBEnumDescriptorProto*) getEnumType:(int32_t) index;
- (PBDescriptorProto_Builder*) setEnumType:(int32_t) index value:(PBEnumDescriptorProto*) value;
- (PBDescriptorProto_Builder*) setEnumType:(int32_t) index builderForValue:(PBEnumDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addEnumTypeBuilder:(PBEnumDescriptorProto_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (PBDescriptorProto_Builder*) clearEnumType;
- (PBDescriptorProto_Builder*) addEnumType:(PBEnumDescriptorProto*) value;

// repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;
- (NSArray*) getExtensionRangeList;
- (int32_t) getExtensionRangeCount;
- (PBExtensionRange*) getExtensionRange:(int32_t) index;
- (PBDescriptorProto_Builder*) setExtensionRange:(int32_t) index value:(PBExtensionRange*) value;
- (PBDescriptorProto_Builder*) setExtensionRange:(int32_t) index builderForValue:(PBExtensionRange_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addExtensionRangeBuilder:(PBExtensionRange_Builder*) builderForValue;
- (PBDescriptorProto_Builder*) addAllExtensionRange:(NSArray*) values;
- (PBDescriptorProto_Builder*) clearExtensionRange;
- (PBDescriptorProto_Builder*) addExtensionRange:(PBExtensionRange*) value;

// optional .google.protobuf.MessageOptions options = 7;
- (BOOL) hasOptions;
- (PBMessageOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBMessageOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBMessageOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBMessageOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBFieldDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional int32 number = 3;
    BOOL hasNumber;
    int32_t number_;
    // optional .google.protobuf.FieldDescriptorProto.Label label = 4;
    BOOL hasLabel;
    PBLabel* label_;
    // optional .google.protobuf.FieldDescriptorProto.Type type = 5;
    BOOL hasType;
    PBType* type_;
    // optional string type_name = 6;
    BOOL hasTypeName;
    NSString* typeName_;
    // optional string extendee = 2;
    BOOL hasExtendee;
    NSString* extendee_;
    // optional string default_value = 7;
    BOOL hasDefaultValue;
    NSString* defaultValue_;
    // optional .google.protobuf.FieldOptions options = 8;
    BOOL hasOptions;
    PBFieldOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasNumber;
@property int32_t number_;
@property BOOL hasLabel;
@property (retain) PBLabel* label_;
@property BOOL hasType;
@property (retain) PBType* type_;
@property BOOL hasTypeName;
@property (retain) NSString* typeName_;
@property BOOL hasExtendee;
@property (retain) NSString* extendee_;
@property BOOL hasDefaultValue;
@property (retain) NSString* defaultValue_;
@property BOOL hasOptions;
@property (retain) PBFieldOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (BOOL) hasLabel;
- (PBLabel*) getLabel;
- (BOOL) hasType;
- (PBType*) getType;
- (BOOL) hasTypeName;
- (NSString*) getTypeName;
- (BOOL) hasExtendee;
- (NSString*) getExtendee;
- (BOOL) hasDefaultValue;
- (NSString*) getDefaultValue;
- (PBFieldOptions*) getOptions;
+ (PBFieldDescriptorProto*) getDefaultInstance;
- (PBFieldDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBFieldDescriptorProto_Builder*) newBuilder;
- (PBFieldDescriptorProto_Builder*) newBuilderForType;
+ (PBFieldDescriptorProto_Builder*) newBuilderWithPBFieldDescriptorProto:(PBFieldDescriptorProto*) prototype;
+ (PBFieldDescriptorProto*) parseFromData:(NSData*) data;
+ (PBFieldDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFieldDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBFieldDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBType : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (PBType*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (PBType*) TYPE_DOUBLE;
+ (PBType*) TYPE_FLOAT;
+ (PBType*) TYPE_INT64;
+ (PBType*) TYPE_UINT64;
+ (PBType*) TYPE_INT32;
+ (PBType*) TYPE_FIXED64;
+ (PBType*) TYPE_FIXED32;
+ (PBType*) TYPE_BOOL_;
+ (PBType*) TYPE_STRING;
+ (PBType*) TYPE_GROUP;
+ (PBType*) TYPE_MESSAGE;
+ (PBType*) TYPE_BYTES;
+ (PBType*) TYPE_UINT32;
+ (PBType*) TYPE_ENUM;
+ (PBType*) TYPE_SFIXED32;
+ (PBType*) TYPE_SFIXED64;
+ (PBType*) TYPE_SINT32;
+ (PBType*) TYPE_SINT64;

- (int32_t) getNumber;
+ (PBType*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (PBType*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface PBLabel : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (PBLabel*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (PBLabel*) LABEL_OPTIONAL;
+ (PBLabel*) LABEL_REQUIRED;
+ (PBLabel*) LABEL_REPEATED;

- (int32_t) getNumber;
+ (PBLabel*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (PBLabel*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface PBFieldDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBFieldDescriptorProto* result;
}
@property (retain) PBFieldDescriptorProto* result;
// Construct using PBFieldDescriptorProto.newBuilder()
- (PBFieldDescriptorProto_Builder*) clear;
- (PBFieldDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBFieldDescriptorProto*) getDefaultInstanceForType;
- (PBFieldDescriptorProto*) build;
- (PBFieldDescriptorProto*) buildParsed;
- (PBFieldDescriptorProto*) buildPartial;
- (PBFieldDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBFieldDescriptorProto_Builder*) mergeFromPBFieldDescriptorProto:(PBFieldDescriptorProto*) other;
- (PBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBFieldDescriptorProto_Builder*) setName:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearName;

// optional int32 number = 3;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (PBFieldDescriptorProto_Builder*) setNumber:(int32_t) value;
- (PBFieldDescriptorProto_Builder*) clearNumber;

// optional .google.protobuf.FieldDescriptorProto.Label label = 4;
- (BOOL) hasLabel;
- (PBLabel*) getLabel;
- (PBFieldDescriptorProto_Builder*) setLabel:(PBLabel*) value;
- (PBFieldDescriptorProto_Builder*) clearLabel;

// optional .google.protobuf.FieldDescriptorProto.Type type = 5;
- (BOOL) hasType;
- (PBType*) getType;
- (PBFieldDescriptorProto_Builder*) setType:(PBType*) value;
- (PBFieldDescriptorProto_Builder*) clearType;

// optional string type_name = 6;
- (BOOL) hasTypeName;
- (NSString*) getTypeName;
- (PBFieldDescriptorProto_Builder*) setTypeName:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearTypeName;

// optional string extendee = 2;
- (BOOL) hasExtendee;
- (NSString*) getExtendee;
- (PBFieldDescriptorProto_Builder*) setExtendee:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearExtendee;

// optional string default_value = 7;
- (BOOL) hasDefaultValue;
- (NSString*) getDefaultValue;
- (PBFieldDescriptorProto_Builder*) setDefaultValue:(NSString*) value;
- (PBFieldDescriptorProto_Builder*) clearDefaultValue;

// optional .google.protobuf.FieldOptions options = 8;
- (BOOL) hasOptions;
- (PBFieldOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBFieldOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBFieldOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBFieldOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBEnumDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.EnumValueDescriptorProto value = 2;
    NSMutableArray* value_;
    // optional .google.protobuf.EnumOptions options = 3;
    BOOL hasOptions;
    PBEnumOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* value_;
@property BOOL hasOptions;
@property (retain) PBEnumOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getValueList;
- (int32_t) getValueCount;
- (PBEnumValueDescriptorProto*) getValue:(int32_t) index;
- (PBEnumOptions*) getOptions;
+ (PBEnumDescriptorProto*) getDefaultInstance;
- (PBEnumDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBEnumDescriptorProto_Builder*) newBuilder;
- (PBEnumDescriptorProto_Builder*) newBuilderForType;
+ (PBEnumDescriptorProto_Builder*) newBuilderWithPBEnumDescriptorProto:(PBEnumDescriptorProto*) prototype;
+ (PBEnumDescriptorProto*) parseFromData:(NSData*) data;
+ (PBEnumDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBEnumDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBEnumDescriptorProto* result;
}
@property (retain) PBEnumDescriptorProto* result;
// Construct using PBEnumDescriptorProto.newBuilder()
- (PBEnumDescriptorProto_Builder*) clear;
- (PBEnumDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBEnumDescriptorProto*) getDefaultInstanceForType;
- (PBEnumDescriptorProto*) build;
- (PBEnumDescriptorProto*) buildParsed;
- (PBEnumDescriptorProto*) buildPartial;
- (PBEnumDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBEnumDescriptorProto_Builder*) mergeFromPBEnumDescriptorProto:(PBEnumDescriptorProto*) other;
- (PBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBEnumDescriptorProto_Builder*) setName:(NSString*) value;
- (PBEnumDescriptorProto_Builder*) clearName;

// repeated .google.protobuf.EnumValueDescriptorProto value = 2;
- (NSArray*) getValueList;
- (int32_t) getValueCount;
- (PBEnumValueDescriptorProto*) getValue:(int32_t) index;
- (PBEnumDescriptorProto_Builder*) setValue:(int32_t) index value:(PBEnumValueDescriptorProto*) value;
- (PBEnumDescriptorProto_Builder*) setValue:(int32_t) index builderForValue:(PBEnumValueDescriptorProto_Builder*) builderForValue;
- (PBEnumDescriptorProto_Builder*) addValueBuilder:(PBEnumValueDescriptorProto_Builder*) builderForValue;
- (PBEnumDescriptorProto_Builder*) addAllValue:(NSArray*) values;
- (PBEnumDescriptorProto_Builder*) clearValue;
- (PBEnumDescriptorProto_Builder*) addValue:(PBEnumValueDescriptorProto*) value;

// optional .google.protobuf.EnumOptions options = 3;
- (BOOL) hasOptions;
- (PBEnumOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBEnumOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBEnumOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBEnumOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBEnumValueDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional int32 number = 2;
    BOOL hasNumber;
    int32_t number_;
    // optional .google.protobuf.EnumValueOptions options = 3;
    BOOL hasOptions;
    PBEnumValueOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasNumber;
@property int32_t number_;
@property BOOL hasOptions;
@property (retain) PBEnumValueOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (PBEnumValueOptions*) getOptions;
+ (PBEnumValueDescriptorProto*) getDefaultInstance;
- (PBEnumValueDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBEnumValueDescriptorProto_Builder*) newBuilder;
- (PBEnumValueDescriptorProto_Builder*) newBuilderForType;
+ (PBEnumValueDescriptorProto_Builder*) newBuilderWithPBEnumValueDescriptorProto:(PBEnumValueDescriptorProto*) prototype;
+ (PBEnumValueDescriptorProto*) parseFromData:(NSData*) data;
+ (PBEnumValueDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumValueDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBEnumValueDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumValueDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBEnumValueDescriptorProto* result;
}
@property (retain) PBEnumValueDescriptorProto* result;
// Construct using PBEnumValueDescriptorProto.newBuilder()
- (PBEnumValueDescriptorProto_Builder*) clear;
- (PBEnumValueDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBEnumValueDescriptorProto*) getDefaultInstanceForType;
- (PBEnumValueDescriptorProto*) build;
- (PBEnumValueDescriptorProto*) buildParsed;
- (PBEnumValueDescriptorProto*) buildPartial;
- (PBEnumValueDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBEnumValueDescriptorProto_Builder*) mergeFromPBEnumValueDescriptorProto:(PBEnumValueDescriptorProto*) other;
- (PBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBEnumValueDescriptorProto_Builder*) setName:(NSString*) value;
- (PBEnumValueDescriptorProto_Builder*) clearName;

// optional int32 number = 2;
- (BOOL) hasNumber;
- (int32_t) getNumber;
- (PBEnumValueDescriptorProto_Builder*) setNumber:(int32_t) value;
- (PBEnumValueDescriptorProto_Builder*) clearNumber;

// optional .google.protobuf.EnumValueOptions options = 3;
- (BOOL) hasOptions;
- (PBEnumValueOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBEnumValueOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBEnumValueOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBEnumValueOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBServiceDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // repeated .google.protobuf.MethodDescriptorProto method = 2;
    NSMutableArray* method_;
    // optional .google.protobuf.ServiceOptions options = 3;
    BOOL hasOptions;
    PBServiceOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property (retain) NSMutableArray* method_;
@property BOOL hasOptions;
@property (retain) PBServiceOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (NSArray*) getMethodList;
- (int32_t) getMethodCount;
- (PBMethodDescriptorProto*) getMethod:(int32_t) index;
- (PBServiceOptions*) getOptions;
+ (PBServiceDescriptorProto*) getDefaultInstance;
- (PBServiceDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBServiceDescriptorProto_Builder*) newBuilder;
- (PBServiceDescriptorProto_Builder*) newBuilderForType;
+ (PBServiceDescriptorProto_Builder*) newBuilderWithPBServiceDescriptorProto:(PBServiceDescriptorProto*) prototype;
+ (PBServiceDescriptorProto*) parseFromData:(NSData*) data;
+ (PBServiceDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBServiceDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBServiceDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBServiceDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBServiceDescriptorProto* result;
}
@property (retain) PBServiceDescriptorProto* result;
// Construct using PBServiceDescriptorProto.newBuilder()
- (PBServiceDescriptorProto_Builder*) clear;
- (PBServiceDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBServiceDescriptorProto*) getDefaultInstanceForType;
- (PBServiceDescriptorProto*) build;
- (PBServiceDescriptorProto*) buildParsed;
- (PBServiceDescriptorProto*) buildPartial;
- (PBServiceDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBServiceDescriptorProto_Builder*) mergeFromPBServiceDescriptorProto:(PBServiceDescriptorProto*) other;
- (PBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBServiceDescriptorProto_Builder*) setName:(NSString*) value;
- (PBServiceDescriptorProto_Builder*) clearName;

// repeated .google.protobuf.MethodDescriptorProto method = 2;
- (NSArray*) getMethodList;
- (int32_t) getMethodCount;
- (PBMethodDescriptorProto*) getMethod:(int32_t) index;
- (PBServiceDescriptorProto_Builder*) setMethod:(int32_t) index value:(PBMethodDescriptorProto*) value;
- (PBServiceDescriptorProto_Builder*) setMethod:(int32_t) index builderForValue:(PBMethodDescriptorProto_Builder*) builderForValue;
- (PBServiceDescriptorProto_Builder*) addMethodBuilder:(PBMethodDescriptorProto_Builder*) builderForValue;
- (PBServiceDescriptorProto_Builder*) addAllMethod:(NSArray*) values;
- (PBServiceDescriptorProto_Builder*) clearMethod;
- (PBServiceDescriptorProto_Builder*) addMethod:(PBMethodDescriptorProto*) value;

// optional .google.protobuf.ServiceOptions options = 3;
- (BOOL) hasOptions;
- (PBServiceOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBServiceOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBServiceOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBServiceOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBMethodDescriptorProto : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string name = 1;
    BOOL hasName;
    NSString* name_;
    // optional string input_type = 2;
    BOOL hasInputType;
    NSString* inputType_;
    // optional string output_type = 3;
    BOOL hasOutputType;
    NSString* outputType_;
    // optional .google.protobuf.MethodOptions options = 4;
    BOOL hasOptions;
    PBMethodOptions* options_;
}
@property BOOL hasName;
@property (retain) NSString* name_;
@property BOOL hasInputType;
@property (retain) NSString* inputType_;
@property BOOL hasOutputType;
@property (retain) NSString* outputType_;
@property BOOL hasOptions;
@property (retain) PBMethodOptions* options_;
- (BOOL) hasName;
- (NSString*) getName;
- (BOOL) hasInputType;
- (NSString*) getInputType;
- (BOOL) hasOutputType;
- (NSString*) getOutputType;
- (PBMethodOptions*) getOptions;
+ (PBMethodDescriptorProto*) getDefaultInstance;
- (PBMethodDescriptorProto*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBMethodDescriptorProto_Builder*) newBuilder;
- (PBMethodDescriptorProto_Builder*) newBuilderForType;
+ (PBMethodDescriptorProto_Builder*) newBuilderWithPBMethodDescriptorProto:(PBMethodDescriptorProto*) prototype;
+ (PBMethodDescriptorProto*) parseFromData:(NSData*) data;
+ (PBMethodDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (PBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMethodDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBMethodDescriptorProto*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBMethodDescriptorProto_Builder : GeneratedMessage_Builder {
@private
    PBMethodDescriptorProto* result;
}
@property (retain) PBMethodDescriptorProto* result;
// Construct using PBMethodDescriptorProto.newBuilder()
- (PBMethodDescriptorProto_Builder*) clear;
- (PBMethodDescriptorProto_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBMethodDescriptorProto*) getDefaultInstanceForType;
- (PBMethodDescriptorProto*) build;
- (PBMethodDescriptorProto*) buildParsed;
- (PBMethodDescriptorProto*) buildPartial;
- (PBMethodDescriptorProto_Builder*) mergeFromMessage:(id<Message>) other;
- (PBMethodDescriptorProto_Builder*) mergeFromPBMethodDescriptorProto:(PBMethodDescriptorProto*) other;
- (PBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string name = 1;
- (BOOL) hasName;
- (NSString*) getName;
- (PBMethodDescriptorProto_Builder*) setName:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearName;

// optional string input_type = 2;
- (BOOL) hasInputType;
- (NSString*) getInputType;
- (PBMethodDescriptorProto_Builder*) setInputType:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearInputType;

// optional string output_type = 3;
- (BOOL) hasOutputType;
- (NSString*) getOutputType;
- (PBMethodDescriptorProto_Builder*) setOutputType:(NSString*) value;
- (PBMethodDescriptorProto_Builder*) clearOutputType;

// optional .google.protobuf.MethodOptions options = 4;
- (BOOL) hasOptions;
- (PBMethodOptions*) getOptions;
- (id<Message_Builder>) setOptions:(PBMethodOptions*) value;
- (id<Message_Builder>) setOptionsBuilder:(PBMethodOptions_Builder*) builderForValue;
- (id<Message_Builder>) mergeOptions:(PBMethodOptions*) value;
- (id<Message_Builder>) clearOptions;
@end

@interface PBFileOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional string java_package = 1;
    BOOL hasJavaPackage;
    NSString* javaPackage_;
    // optional string java_outer_classname = 8;
    BOOL hasJavaOuterClassname;
    NSString* javaOuterClassname_;
    // optional bool java_multiple_files = 10 [default = false];
    BOOL hasJavaMultipleFiles;
    BOOL javaMultipleFiles_;
    // optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = CODE_SIZE];
    BOOL hasOptimizeFor;
    PBOptimizeMode* optimizeFor_;
    // optional string objectivec_package = 11;
    BOOL hasObjectivecPackage;
    NSString* objectivecPackage_;
    // optional string objectivec_class_prefix = 12;
    BOOL hasObjectivecClassPrefix;
    NSString* objectivecClassPrefix_;
}
@property BOOL hasJavaPackage;
@property (retain) NSString* javaPackage_;
@property BOOL hasJavaOuterClassname;
@property (retain) NSString* javaOuterClassname_;
@property BOOL hasJavaMultipleFiles;
@property BOOL javaMultipleFiles_;
@property BOOL hasOptimizeFor;
@property (retain) PBOptimizeMode* optimizeFor_;
@property BOOL hasObjectivecPackage;
@property (retain) NSString* objectivecPackage_;
@property BOOL hasObjectivecClassPrefix;
@property (retain) NSString* objectivecClassPrefix_;
- (BOOL) hasJavaPackage;
- (NSString*) getJavaPackage;
- (BOOL) hasJavaOuterClassname;
- (NSString*) getJavaOuterClassname;
- (BOOL) hasJavaMultipleFiles;
- (BOOL) getJavaMultipleFiles;
- (BOOL) hasOptimizeFor;
- (PBOptimizeMode*) getOptimizeFor;
- (BOOL) hasObjectivecPackage;
- (NSString*) getObjectivecPackage;
- (BOOL) hasObjectivecClassPrefix;
- (NSString*) getObjectivecClassPrefix;
+ (PBFileOptions*) getDefaultInstance;
- (PBFileOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBFileOptions_Builder*) newBuilder;
- (PBFileOptions_Builder*) newBuilderForType;
+ (PBFileOptions_Builder*) newBuilderWithPBFileOptions:(PBFileOptions*) prototype;
+ (PBFileOptions*) parseFromData:(NSData*) data;
+ (PBFileOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBFileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFileOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBFileOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBOptimizeMode : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (PBOptimizeMode*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (PBOptimizeMode*) SPEED;
+ (PBOptimizeMode*) CODE_SIZE;

- (int32_t) getNumber;
+ (PBOptimizeMode*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (PBOptimizeMode*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface PBFileOptions_Builder : GeneratedMessage_Builder {
@private
    PBFileOptions* result;
}
@property (retain) PBFileOptions* result;
// Construct using PBFileOptions.newBuilder()
- (PBFileOptions_Builder*) clear;
- (PBFileOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBFileOptions*) getDefaultInstanceForType;
- (PBFileOptions*) build;
- (PBFileOptions*) buildParsed;
- (PBFileOptions*) buildPartial;
- (PBFileOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBFileOptions_Builder*) mergeFromPBFileOptions:(PBFileOptions*) other;
- (PBFileOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBFileOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional string java_package = 1;
- (BOOL) hasJavaPackage;
- (NSString*) getJavaPackage;
- (PBFileOptions_Builder*) setJavaPackage:(NSString*) value;
- (PBFileOptions_Builder*) clearJavaPackage;

// optional string java_outer_classname = 8;
- (BOOL) hasJavaOuterClassname;
- (NSString*) getJavaOuterClassname;
- (PBFileOptions_Builder*) setJavaOuterClassname:(NSString*) value;
- (PBFileOptions_Builder*) clearJavaOuterClassname;

// optional bool java_multiple_files = 10 [default = false];
- (BOOL) hasJavaMultipleFiles;
- (BOOL) getJavaMultipleFiles;
- (PBFileOptions_Builder*) setJavaMultipleFiles:(BOOL) value;
- (PBFileOptions_Builder*) clearJavaMultipleFiles;

// optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = CODE_SIZE];
- (BOOL) hasOptimizeFor;
- (PBOptimizeMode*) getOptimizeFor;
- (PBFileOptions_Builder*) setOptimizeFor:(PBOptimizeMode*) value;
- (PBFileOptions_Builder*) clearOptimizeFor;

// optional string objectivec_package = 11;
- (BOOL) hasObjectivecPackage;
- (NSString*) getObjectivecPackage;
- (PBFileOptions_Builder*) setObjectivecPackage:(NSString*) value;
- (PBFileOptions_Builder*) clearObjectivecPackage;

// optional string objectivec_class_prefix = 12;
- (BOOL) hasObjectivecClassPrefix;
- (NSString*) getObjectivecClassPrefix;
- (PBFileOptions_Builder*) setObjectivecClassPrefix:(NSString*) value;
- (PBFileOptions_Builder*) clearObjectivecClassPrefix;
@end

@interface PBMessageOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional bool message_set_wire_format = 1 [default = false];
    BOOL hasMessageSetWireFormat;
    BOOL messageSetWireFormat_;
}
@property BOOL hasMessageSetWireFormat;
@property BOOL messageSetWireFormat_;
- (BOOL) hasMessageSetWireFormat;
- (BOOL) getMessageSetWireFormat;
+ (PBMessageOptions*) getDefaultInstance;
- (PBMessageOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBMessageOptions_Builder*) newBuilder;
- (PBMessageOptions_Builder*) newBuilderForType;
+ (PBMessageOptions_Builder*) newBuilderWithPBMessageOptions:(PBMessageOptions*) prototype;
+ (PBMessageOptions*) parseFromData:(NSData*) data;
+ (PBMessageOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMessageOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBMessageOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMessageOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBMessageOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBMessageOptions_Builder : GeneratedMessage_Builder {
@private
    PBMessageOptions* result;
}
@property (retain) PBMessageOptions* result;
// Construct using PBMessageOptions.newBuilder()
- (PBMessageOptions_Builder*) clear;
- (PBMessageOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBMessageOptions*) getDefaultInstanceForType;
- (PBMessageOptions*) build;
- (PBMessageOptions*) buildParsed;
- (PBMessageOptions*) buildPartial;
- (PBMessageOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBMessageOptions_Builder*) mergeFromPBMessageOptions:(PBMessageOptions*) other;
- (PBMessageOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBMessageOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional bool message_set_wire_format = 1 [default = false];
- (BOOL) hasMessageSetWireFormat;
- (BOOL) getMessageSetWireFormat;
- (PBMessageOptions_Builder*) setMessageSetWireFormat:(BOOL) value;
- (PBMessageOptions_Builder*) clearMessageSetWireFormat;
@end

@interface PBFieldOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
    // optional .google.protobuf.FieldOptions.CType ctype = 1;
    BOOL hasCtype;
    PBCType* ctype_;
    // optional string experimental_map_key = 9;
    BOOL hasExperimentalMapKey;
    NSString* experimentalMapKey_;
}
@property BOOL hasCtype;
@property (retain) PBCType* ctype_;
@property BOOL hasExperimentalMapKey;
@property (retain) NSString* experimentalMapKey_;
- (BOOL) hasCtype;
- (PBCType*) getCtype;
- (BOOL) hasExperimentalMapKey;
- (NSString*) getExperimentalMapKey;
+ (PBFieldOptions*) getDefaultInstance;
- (PBFieldOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBFieldOptions_Builder*) newBuilder;
- (PBFieldOptions_Builder*) newBuilderForType;
+ (PBFieldOptions_Builder*) newBuilderWithPBFieldOptions:(PBFieldOptions*) prototype;
+ (PBFieldOptions*) parseFromData:(NSData*) data;
+ (PBFieldOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFieldOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBFieldOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBFieldOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBFieldOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBCType : NSObject {
@private
    int32_t index;
    int32_t value;
}
@property int32_t index;
@property int32_t value;
+ (PBCType*) newWithIndex:(int32_t) index value:(int32_t) value;
+ (PBCType*) CORD;
+ (PBCType*) STRING_PIECE;

- (int32_t) getNumber;
+ (PBCType*) valueOf:(int32_t) value;
- (EnumValueDescriptor*) getValueDescriptor;
- (EnumDescriptor*) getDescriptorForType;
+ (EnumDescriptor*) getDescriptor;

+ (PBCType*) valueOfDescriptor:(EnumValueDescriptor*) desc;
@end

@interface PBFieldOptions_Builder : GeneratedMessage_Builder {
@private
    PBFieldOptions* result;
}
@property (retain) PBFieldOptions* result;
// Construct using PBFieldOptions.newBuilder()
- (PBFieldOptions_Builder*) clear;
- (PBFieldOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBFieldOptions*) getDefaultInstanceForType;
- (PBFieldOptions*) build;
- (PBFieldOptions*) buildParsed;
- (PBFieldOptions*) buildPartial;
- (PBFieldOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBFieldOptions_Builder*) mergeFromPBFieldOptions:(PBFieldOptions*) other;
- (PBFieldOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBFieldOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;

// optional .google.protobuf.FieldOptions.CType ctype = 1;
- (BOOL) hasCtype;
- (PBCType*) getCtype;
- (PBFieldOptions_Builder*) setCtype:(PBCType*) value;
- (PBFieldOptions_Builder*) clearCtype;

// optional string experimental_map_key = 9;
- (BOOL) hasExperimentalMapKey;
- (NSString*) getExperimentalMapKey;
- (PBFieldOptions_Builder*) setExperimentalMapKey:(NSString*) value;
- (PBFieldOptions_Builder*) clearExperimentalMapKey;
@end

@interface PBEnumOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (PBEnumOptions*) getDefaultInstance;
- (PBEnumOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBEnumOptions_Builder*) newBuilder;
- (PBEnumOptions_Builder*) newBuilderForType;
+ (PBEnumOptions_Builder*) newBuilderWithPBEnumOptions:(PBEnumOptions*) prototype;
+ (PBEnumOptions*) parseFromData:(NSData*) data;
+ (PBEnumOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBEnumOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumOptions_Builder : GeneratedMessage_Builder {
@private
    PBEnumOptions* result;
}
@property (retain) PBEnumOptions* result;
// Construct using PBEnumOptions.newBuilder()
- (PBEnumOptions_Builder*) clear;
- (PBEnumOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBEnumOptions*) getDefaultInstanceForType;
- (PBEnumOptions*) build;
- (PBEnumOptions*) buildParsed;
- (PBEnumOptions*) buildPartial;
- (PBEnumOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBEnumOptions_Builder*) mergeFromPBEnumOptions:(PBEnumOptions*) other;
- (PBEnumOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBEnumOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumValueOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (PBEnumValueOptions*) getDefaultInstance;
- (PBEnumValueOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBEnumValueOptions_Builder*) newBuilder;
- (PBEnumValueOptions_Builder*) newBuilderForType;
+ (PBEnumValueOptions_Builder*) newBuilderWithPBEnumValueOptions:(PBEnumValueOptions*) prototype;
+ (PBEnumValueOptions*) parseFromData:(NSData*) data;
+ (PBEnumValueOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBEnumValueOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBEnumValueOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBEnumValueOptions_Builder : GeneratedMessage_Builder {
@private
    PBEnumValueOptions* result;
}
@property (retain) PBEnumValueOptions* result;
// Construct using PBEnumValueOptions.newBuilder()
- (PBEnumValueOptions_Builder*) clear;
- (PBEnumValueOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBEnumValueOptions*) getDefaultInstanceForType;
- (PBEnumValueOptions*) build;
- (PBEnumValueOptions*) buildParsed;
- (PBEnumValueOptions*) buildPartial;
- (PBEnumValueOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBEnumValueOptions_Builder*) mergeFromPBEnumValueOptions:(PBEnumValueOptions*) other;
- (PBEnumValueOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBEnumValueOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBServiceOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (PBServiceOptions*) getDefaultInstance;
- (PBServiceOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBServiceOptions_Builder*) newBuilder;
- (PBServiceOptions_Builder*) newBuilderForType;
+ (PBServiceOptions_Builder*) newBuilderWithPBServiceOptions:(PBServiceOptions*) prototype;
+ (PBServiceOptions*) parseFromData:(NSData*) data;
+ (PBServiceOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBServiceOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBServiceOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBServiceOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBServiceOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBServiceOptions_Builder : GeneratedMessage_Builder {
@private
    PBServiceOptions* result;
}
@property (retain) PBServiceOptions* result;
// Construct using PBServiceOptions.newBuilder()
- (PBServiceOptions_Builder*) clear;
- (PBServiceOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBServiceOptions*) getDefaultInstanceForType;
- (PBServiceOptions*) build;
- (PBServiceOptions*) buildParsed;
- (PBServiceOptions*) buildPartial;
- (PBServiceOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBServiceOptions_Builder*) mergeFromPBServiceOptions:(PBServiceOptions*) other;
- (PBServiceOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBServiceOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBMethodOptions : GeneratedMessage {
@private
    int32_t memoizedSerializedSize;
}
+ (PBMethodOptions*) getDefaultInstance;
- (PBMethodOptions*) getDefaultInstanceForType;
+ (Descriptor*) getDescriptor;
- (FieldAccessorTable*) internalGetFieldAccessorTable;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(CodedOutputStream*) output;
+ (PBMethodOptions_Builder*) newBuilder;
- (PBMethodOptions_Builder*) newBuilderForType;
+ (PBMethodOptions_Builder*) newBuilderWithPBMethodOptions:(PBMethodOptions*) prototype;
+ (PBMethodOptions*) parseFromData:(NSData*) data;
+ (PBMethodOptions*) parseFromData:(NSData*) data extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMethodOptions*) parseFromInputStream:(NSInputStream*) input;
+ (PBMethodOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
+ (PBMethodOptions*) parseFromCodedInputStream:(CodedInputStream*) input;
+ (PBMethodOptions*) parseFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

@interface PBMethodOptions_Builder : GeneratedMessage_Builder {
@private
    PBMethodOptions* result;
}
@property (retain) PBMethodOptions* result;
// Construct using PBMethodOptions.newBuilder()
- (PBMethodOptions_Builder*) clear;
- (PBMethodOptions_Builder*) clone;
- (Descriptor*) getDescriptorForType;
- (PBMethodOptions*) getDefaultInstanceForType;
- (PBMethodOptions*) build;
- (PBMethodOptions*) buildParsed;
- (PBMethodOptions*) buildPartial;
- (PBMethodOptions_Builder*) mergeFromMessage:(id<Message>) other;
- (PBMethodOptions_Builder*) mergeFromPBMethodOptions:(PBMethodOptions*) other;
- (PBMethodOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input;
- (PBMethodOptions_Builder*) mergeFromCodedInputStream:(CodedInputStream*) input extensionRegistry:(ExtensionRegistry*) extensionRegistry;
@end

